-- =============================================================================
-- 0032 — KONU SÖZLÜĞÜNÜ ALT BAŞLIK SEVİYESİNE İNDİR (Kunduz derinliği)
--
-- NEDEN: 0027/0029/0031'in sözlüğü ÖSYM'nin yayımlanan konu listesi seviyesindeydi:
-- "Optik" tek satırdı, "Türev" tek satırdı. Öğrenci "Küresel Aynalar çalışacağım"
-- diyor, ekranda öyle bir başlık yoktu. Bu migration sözlüğü kunduz.com'un ünite/konu
-- kırılımına indiriyor: Optik → 8 konu, Türev → 11 konu, Sayma ve Olasılık → Binom
-- Açılımı ve Pascal Üçgeni ayrı satır.
--
--   313 konu → 752 konu · 168 ünite
--
-- KAYNAK: kunduz.com /tr/hazirlik/<sinav>-<ders>/ ünite listeleri + /tr/konular/<unite>/
-- alt konu sayfaları (2026-07-28 hasadı). Kunduz'un ürün artıkları ("… Yeni Nesil
-- Sorular", "… Örnek Sorular") sözlüğe ALINMADI — onlar konu değil, içerik etiketi.
--
-- KAPSAM DIŞI: Felsefe, Din Kültürü ve Ahlak Bilgisi, Mantık, Psikoloji, Sosyoloji.
-- Kunduz bu dersleri hiç kapsamıyor; satırlarına DOKUNULMUYOR.
--
-- ⚠️ VERİ GÜVENLİĞİ: kazanim_konu.konu_id ve konu_talep.konu_id bu tabloya FK ile
-- bağlı ve ON DELETE CASCADE. Sözlüğü silmek onları da siler. Bu yüzden migration
-- ikisinin de BOŞ olduğunu doğrulamadan devam etmiyor — dolu olsalardı sessiz veri
-- kaybı olurdu. (Eşleme bu migration'dan SONRA yeni sözlükle koşulacak.)
-- =============================================================================
set search_path to public, extensions;

begin;

-- 1) Güvenlik kapısı — bağlı tablolar boş değilse migration DURUR.
do $guvenlik$
declare n bigint;
begin
  select count(*) into n from public.kazanim_konu;
  if n > 0 then
    raise exception 'kazanim_konu % satır içeriyor. Sözlük değişimi bunları silerdi. Önce yedekle, sonra bu kontrolü kaldır.', n;
  end if;
  select count(*) into n from public.konu_talep;
  if n > 0 then
    raise exception 'konu_talep % satır içeriyor (öğrenci talepleri). Önce yedekle.', n;
  end if;
end
$guvenlik$;

-- 2) View konular'a bağlı — silmeden önce kaldır, sonunda aynen geri kur.
drop view if exists public.konu_havuz;

-- 3) Kunduz kapsamındaki derslerin eski satırlarını sil.
delete from public.konular
 where subject in ('Fizik', 'Kimya', 'Biyoloji', 'Matematik', 'Türkçe', 'Tarih', 'Coğrafya', 'Türk Dili ve Edebiyatı');

-- 4) Yeni sözlük.
insert into public.konular (subject, ad, sinav, unite, unite_sira, sira) values
  ('Fizik', 'Fizik Bilimine Giriş', 'TYT', 'Fizik Bilimine Giriş', 1, 1),
  ('Fizik', 'Fiziksel Nicelikler', 'TYT', 'Fizik Bilimine Giriş', 1, 2),
  ('Fizik', 'Bilim Araştırma Merkezleri', 'TYT', 'Fizik Bilimine Giriş', 1, 3),
  ('Fizik', 'Madde ve Özkütle', 'TYT', 'Madde ve Özellikleri', 2, 4),
  ('Fizik', 'Adezyon ve Kohezyon', 'TYT', 'Madde ve Özellikleri', 2, 5),
  ('Fizik', 'Dayanıklılık', 'TYT', 'Madde ve Özellikleri', 2, 6),
  ('Fizik', 'Hareket', 'TYT', 'Hareket ve Kuvvet', 3, 7),
  ('Fizik', 'Kuvvet', 'TYT', 'Hareket ve Kuvvet', 3, 8),
  ('Fizik', 'Newton''un Hareket Yasaları ve Sürtünme Kuvveti', 'TYT', 'Hareket ve Kuvvet', 3, 9),
  ('Fizik', 'Doğadaki Temel Kuvvetler', 'TYT', 'Hareket ve Kuvvet', 3, 10),
  ('Fizik', 'İş, Enerji ve Güç', 'TYT', 'Enerji', 4, 11),
  ('Fizik', 'Mekanik Enerji', 'TYT', 'Enerji', 4, 12),
  ('Fizik', 'Enerjinin Korunumu ve Enerji Dönüşümleri', 'TYT', 'Enerji', 4, 13),
  ('Fizik', 'Verim ve Enerji Kaynakları', 'TYT', 'Enerji', 4, 14),
  ('Fizik', 'Isı ve Sıcaklık', 'TYT', 'Isı ve Sıcaklık', 5, 15),
  ('Fizik', 'Hâl Değişimi ve Isıl Denge', 'TYT', 'Isı ve Sıcaklık', 5, 16),
  ('Fizik', 'Enerji İletim Yolları ve Enerji İletim Hızı', 'TYT', 'Isı ve Sıcaklık', 5, 17),
  ('Fizik', 'Genleşme', 'TYT', 'Isı ve Sıcaklık', 5, 18),
  ('Fizik', 'Elektrik Yükleri', 'TYT', 'Elektrostatik', 6, 19),
  ('Fizik', 'Elektrostatik Kuvvet ve Elektriksel Alan', 'TYT', 'Elektrostatik', 6, 20),
  ('Fizik', 'Elektrik Akımı, Potansiyel Farkı ve Direnç', 'TYT', 'Elektrik ve Manyetizma', 7, 21),
  ('Fizik', 'Elektrik Devreleri', 'TYT', 'Elektrik ve Manyetizma', 7, 22),
  ('Fizik', 'Mıknatıs ve Manyetik Alan', 'TYT', 'Elektrik ve Manyetizma', 7, 23),
  ('Fizik', 'Akım ve Manyetik Alan', 'TYT', 'Elektrik ve Manyetizma', 7, 24),
  ('Fizik', 'Basınç', 'TYT', 'Basınç ve Kaldırma Kuvveti', 8, 25),
  ('Fizik', 'Katı Basıncı', 'TYT', 'Basınç ve Kaldırma Kuvveti', 8, 26),
  ('Fizik', 'Sıvı Basıncı', 'TYT', 'Basınç ve Kaldırma Kuvveti', 8, 27),
  ('Fizik', 'Gaz Basıncı', 'TYT', 'Basınç ve Kaldırma Kuvveti', 8, 28),
  ('Fizik', 'Akışkanların Basıncı', 'TYT', 'Basınç ve Kaldırma Kuvveti', 8, 29),
  ('Fizik', 'Kaldırma Kuvveti', 'TYT', 'Basınç ve Kaldırma Kuvveti', 8, 30),
  ('Fizik', 'Dalgaların Genel Özellikleri', 'TYT', 'Dalgalar', 9, 31),
  ('Fizik', 'Yay Dalgaları', 'TYT', 'Dalgalar', 9, 32),
  ('Fizik', 'Su Dalgaları', 'TYT', 'Dalgalar', 9, 33),
  ('Fizik', 'Ses ve Deprem Dalgaları', 'TYT', 'Dalgalar', 9, 34),
  ('Fizik', 'Aydınlanma', 'TYT', 'Optik', 10, 35),
  ('Fizik', 'Gölge', 'TYT', 'Optik', 10, 36),
  ('Fizik', 'Düzlem Ayna', 'TYT', 'Optik', 10, 37),
  ('Fizik', 'Yansıma', 'TYT', 'Optik', 10, 38),
  ('Fizik', 'Küresel Aynalar', 'TYT', 'Optik', 10, 39),
  ('Fizik', 'Kırılma', 'TYT', 'Optik', 10, 40),
  ('Fizik', 'Mercekler', 'TYT', 'Optik', 10, 41),
  ('Fizik', 'Prizmalar ve Renk', 'TYT', 'Optik', 10, 42),
  ('Fizik', 'Vektörler', 'AYT', 'Kuvvet ve Hareket', 1, 1),
  ('Fizik', 'Bağıl Hareket', 'AYT', 'Kuvvet ve Hareket', 1, 2),
  ('Fizik', 'Newton''un Hareket Yasaları', 'AYT', 'Kuvvet ve Hareket', 1, 3),
  ('Fizik', 'Bir Boyutta Sabit İvmeli Hareket', 'AYT', 'Kuvvet ve Hareket', 1, 4),
  ('Fizik', 'İki Boyutta Hareket', 'AYT', 'Kuvvet ve Hareket', 1, 5),
  ('Fizik', 'Enerji ve Hareket', 'AYT', 'Kuvvet ve Hareket', 1, 6),
  ('Fizik', 'İtme ve Çizgisel Momentum', 'AYT', 'Kuvvet ve Hareket', 1, 7),
  ('Fizik', 'Tork', 'AYT', 'Kuvvet ve Hareket', 1, 8),
  ('Fizik', 'Denge ve Denge Şartları', 'AYT', 'Kuvvet ve Hareket', 1, 9),
  ('Fizik', 'Basit Makineler', 'AYT', 'Kuvvet ve Hareket', 1, 10),
  ('Fizik', 'Elektriksel Kuvvet ve Elektriksel Alan', 'AYT', 'Elektrik ve Manyetizma', 2, 11),
  ('Fizik', 'Elektriksel Potansiyel', 'AYT', 'Elektrik ve Manyetizma', 2, 12),
  ('Fizik', 'Düzgün Elektrik Alan ve Sığa', 'AYT', 'Elektrik ve Manyetizma', 2, 13),
  ('Fizik', 'Manyetizma ve Elektromanyetik İndükleme', 'AYT', 'Elektrik ve Manyetizma', 2, 14),
  ('Fizik', 'Manyetik Akı ve İndüksiyon EMK', 'AYT', 'Elektrik ve Manyetizma', 2, 15),
  ('Fizik', 'Yüklü Parçacıkların Hareketi', 'AYT', 'Elektrik ve Manyetizma', 2, 16),
  ('Fizik', 'Elektrik Motorları ve Dinamolar', 'AYT', 'Elektrik ve Manyetizma', 2, 17),
  ('Fizik', 'Alternatif Akım ve Transformatörler', 'AYT', 'Elektrik ve Manyetizma', 2, 18),
  ('Fizik', 'Düzgün Çembersel Hareket', 'AYT', 'Çembersel Hareket', 3, 19),
  ('Fizik', 'Dönerek Öteleme ve Açısal Momentum', 'AYT', 'Çembersel Hareket', 3, 20),
  ('Fizik', 'Kütle Çekim Kuvveti ve Kepler Kanunları', 'AYT', 'Çembersel Hareket', 3, 21),
  ('Fizik', 'Periyot, Frekans, Geri Çağrıcı Kuvvet, Genlik, Uzanım', 'AYT', 'Basit Harmonik Hareket', 4, 22),
  ('Fizik', 'Konum, Hız, İvme, Kuvvet ve Grafikleri', 'AYT', 'Basit Harmonik Hareket', 4, 23),
  ('Fizik', 'Yay ve Basit Sarkaç', 'AYT', 'Basit Harmonik Hareket', 4, 24),
  ('Fizik', 'Su Dalgalarında Kırınım ve Girişim', 'AYT', 'Dalga Mekaniği', 5, 25),
  ('Fizik', 'Işığın Dalga Doğası', 'AYT', 'Dalga Mekaniği', 5, 26),
  ('Fizik', 'Elektromanyetik Dalgalar', 'AYT', 'Dalga Mekaniği', 5, 27),
  ('Fizik', 'Atom Teorileri', 'AYT', 'Atom Fiziğine Giriş ve Radyoaktivite', 6, 28),
  ('Fizik', 'Büyük Patlama ve Evrenin Oluşumu', 'AYT', 'Atom Fiziğine Giriş ve Radyoaktivite', 6, 29),
  ('Fizik', 'Radyoaktivite', 'AYT', 'Atom Fiziğine Giriş ve Radyoaktivite', 6, 30),
  ('Fizik', 'Özel Görelilik ve Siyah Cisim Işıması', 'AYT', 'Modern Fizik', 7, 31),
  ('Fizik', 'Fotoelektrik Olay', 'AYT', 'Modern Fizik', 7, 32),
  ('Fizik', 'Compton Olayı ve De Broglie Dalga Boyu', 'AYT', 'Modern Fizik', 7, 33),
  ('Fizik', 'Görüntüleme Teknolojileri', 'AYT', 'Modern Fiziğin Teknolojideki Uygulamaları', 8, 34),
  ('Fizik', 'Yarı İletken Teknolojisi', 'AYT', 'Modern Fiziğin Teknolojideki Uygulamaları', 8, 35),
  ('Fizik', 'Süper İletkenler', 'AYT', 'Modern Fiziğin Teknolojideki Uygulamaları', 8, 36),
  ('Fizik', 'Nanoteknoloji', 'AYT', 'Modern Fiziğin Teknolojideki Uygulamaları', 8, 37),
  ('Fizik', 'LASER Işınları', 'AYT', 'Modern Fiziğin Teknolojideki Uygulamaları', 8, 38),
  ('Kimya', 'Simyadan Kimyaya', 'TYT', 'Kimya Bilimi', 1, 1),
  ('Kimya', 'Kimyanın Sembolik Dili', 'TYT', 'Kimya Bilimi', 1, 2),
  ('Kimya', 'Kimya Uygulamalarında İş Sağlığı ve Güvenliği', 'TYT', 'Kimya Bilimi', 1, 3),
  ('Kimya', 'Kimyasal Maddelerin Kullanımı ve Güvenlik', 'TYT', 'Kimya Bilimi', 1, 4),
  ('Kimya', 'Atom Modelleri', 'TYT', 'Atom ve Periyodik Sistem', 2, 5),
  ('Kimya', 'Atomun Yapısı', 'TYT', 'Atom ve Periyodik Sistem', 2, 6),
  ('Kimya', 'Periyodik Sistem', 'TYT', 'Atom ve Periyodik Sistem', 2, 7),
  ('Kimya', 'Kimyasal Türler ve Etkileşimler', 'TYT', 'Kimyasal Türler Arası Etkileşimler', 3, 8),
  ('Kimya', 'Güçlü Etkileşimler', 'TYT', 'Kimyasal Türler Arası Etkileşimler', 3, 9),
  ('Kimya', 'Zayıf Etkileşimler', 'TYT', 'Kimyasal Türler Arası Etkileşimler', 3, 10),
  ('Kimya', 'Maddenin Fiziksel Hâlleri', 'TYT', 'Maddenin Hâlleri', 4, 11),
  ('Kimya', 'Katılar', 'TYT', 'Maddenin Hâlleri', 4, 12),
  ('Kimya', 'Sıvılar', 'TYT', 'Maddenin Hâlleri', 4, 13),
  ('Kimya', 'Gazlar ve Plazma', 'TYT', 'Maddenin Hâlleri', 4, 14),
  ('Kimya', 'Su ve Hayat', 'TYT', 'Doğa ve Kimya', 5, 15),
  ('Kimya', 'Çevre Kimyası', 'TYT', 'Doğa ve Kimya', 5, 16),
  ('Kimya', 'Kimyanın Temel Kanunları', 'TYT', 'Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar', 6, 17),
  ('Kimya', 'Mol Kavramı', 'TYT', 'Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar', 6, 18),
  ('Kimya', 'Kimyasal Tepkimeler ve Denklemler', 'TYT', 'Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar', 6, 19),
  ('Kimya', 'Kimyasal Tepkimelerde Hesaplamalar', 'TYT', 'Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar', 6, 20),
  ('Kimya', 'Asitler ve Bazlar', 'TYT', 'Asitler, Bazlar ve Tuzlar', 7, 21),
  ('Kimya', 'Asitlerin ve Bazların Tepkimeleri', 'TYT', 'Asitler, Bazlar ve Tuzlar', 7, 22),
  ('Kimya', 'Hayatımızda Asitler ve Bazlar', 'TYT', 'Asitler, Bazlar ve Tuzlar', 7, 23),
  ('Kimya', 'Tuzlar', 'TYT', 'Asitler, Bazlar ve Tuzlar', 7, 24),
  ('Kimya', 'Yaygın Günlük Hayat Kimyasalları', 'TYT', 'Kimya Her Yerde', 8, 25),
  ('Kimya', 'Gıdalar', 'TYT', 'Kimya Her Yerde', 8, 26),
  ('Kimya', 'Karışımların Genel Özellikleri', 'TYT', 'Karışımlar', 9, 27),
  ('Kimya', 'Çözünme ve Çözelti Derişimleri', 'TYT', 'Karışımlar', 9, 28),
  ('Kimya', 'Karışımlarda Koligatif Özellikler', 'TYT', 'Karışımlar', 9, 29),
  ('Kimya', 'Karışımları Ayırma Teknikleri', 'TYT', 'Karışımlar', 9, 30),
  ('Kimya', 'Atomun Kuantum Modeli', 'AYT', 'Modern Atom Teorisi', 1, 1),
  ('Kimya', 'Periyodik Sistem ve Elektron Dizilimleri', 'AYT', 'Modern Atom Teorisi', 1, 2),
  ('Kimya', 'Periyodik Özellikler', 'AYT', 'Modern Atom Teorisi', 1, 3),
  ('Kimya', 'Elementleri Tanıyalım', 'AYT', 'Modern Atom Teorisi', 1, 4),
  ('Kimya', 'Yükseltgenme Basamakları', 'AYT', 'Modern Atom Teorisi', 1, 5),
  ('Kimya', 'Gazların Genel Özellikleri', 'AYT', 'Gazlar', 2, 6),
  ('Kimya', 'Gaz Yasaları', 'AYT', 'Gazlar', 2, 7),
  ('Kimya', 'İdeal Gaz Yasası', 'AYT', 'Gazlar', 2, 8),
  ('Kimya', 'Gazlarda Kinetik Teori', 'AYT', 'Gazlar', 2, 9),
  ('Kimya', 'Gaz Karışımları', 'AYT', 'Gazlar', 2, 10),
  ('Kimya', 'Gerçek Gazlar', 'AYT', 'Gazlar', 2, 11),
  ('Kimya', 'Çözücü Çözünen Etkileşimleri', 'AYT', 'Sıvı Çözeltiler ve Çözünürlük', 3, 12),
  ('Kimya', 'Derişim Birimleri', 'AYT', 'Sıvı Çözeltiler ve Çözünürlük', 3, 13),
  ('Kimya', 'Koligatif Özellikler', 'AYT', 'Sıvı Çözeltiler ve Çözünürlük', 3, 14),
  ('Kimya', 'Çözünürlük', 'AYT', 'Sıvı Çözeltiler ve Çözünürlük', 3, 15),
  ('Kimya', 'Tepkimelerde Isı Değişimi', 'AYT', 'Kimyasal Tepkimelerde Enerji', 4, 16),
  ('Kimya', 'Oluşum Entalpisi', 'AYT', 'Kimyasal Tepkimelerde Enerji', 4, 17),
  ('Kimya', 'Bağ Enerjileri ve Hess Yasası', 'AYT', 'Kimyasal Tepkimelerde Enerji', 4, 18),
  ('Kimya', 'Tepkime Hızları', 'AYT', 'Kimyasal Tepkimelerde Hız', 5, 19),
  ('Kimya', 'Tepkime Hızını Etkileyen Faktörler', 'AYT', 'Kimyasal Tepkimelerde Hız', 5, 20),
  ('Kimya', 'Kimyasal Denge', 'AYT', 'Kimyasal Tepkimelerde Denge', 6, 21),
  ('Kimya', 'Dengeyi Etkileyen Faktörler', 'AYT', 'Kimyasal Tepkimelerde Denge', 6, 22),
  ('Kimya', 'Sulu Çözelti Dengeleri', 'AYT', 'Kimyasal Tepkimelerde Denge', 6, 23),
  ('Kimya', 'İndirgenme Yükseltgenme Tepkimeleri', 'AYT', 'Kimya ve Elektrik', 7, 24),
  ('Kimya', 'Elektrot Potansiyelleri', 'AYT', 'Kimya ve Elektrik', 7, 25),
  ('Kimya', 'Elektroliz', 'AYT', 'Kimya ve Elektrik', 7, 26),
  ('Kimya', 'Organik Kimyaya Giriş', 'AYT', 'Karbon Kimyasına Giriş', 8, 27),
  ('Kimya', 'Hibritleşme ve Molekül Geometrileri', 'AYT', 'Karbon Kimyasına Giriş', 8, 28),
  ('Kimya', 'Hidrokarbonlar', 'AYT', 'Organik Bileşikler', 9, 29),
  ('Kimya', 'Alkenler', 'AYT', 'Organik Bileşikler', 9, 30),
  ('Kimya', 'Alkinler', 'AYT', 'Organik Bileşikler', 9, 31),
  ('Kimya', 'Fonksiyonel Gruplar', 'AYT', 'Organik Bileşikler', 9, 32),
  ('Kimya', 'Alkoller', 'AYT', 'Organik Bileşikler', 9, 33),
  ('Kimya', 'Eterler', 'AYT', 'Organik Bileşikler', 9, 34),
  ('Kimya', 'Esterler', 'AYT', 'Organik Bileşikler', 9, 35),
  ('Kimya', 'Karbonil Bileşikleri', 'AYT', 'Organik Bileşikler', 9, 36),
  ('Kimya', 'Karboksilli Asitler', 'AYT', 'Organik Bileşikler', 9, 37),
  ('Kimya', 'Fosil Yakıtlar', 'AYT', 'Enerji Kaynakları ve Bilimsel Gelişmeler', 10, 38),
  ('Kimya', 'Alternatif Enerji Kaynakları', 'AYT', 'Enerji Kaynakları ve Bilimsel Gelişmeler', 10, 39),
  ('Kimya', 'Sürdürülebilirlik', 'AYT', 'Enerji Kaynakları ve Bilimsel Gelişmeler', 10, 40),
  ('Kimya', 'Nanoteknoloji', 'AYT', 'Enerji Kaynakları ve Bilimsel Gelişmeler', 10, 41),
  ('Biyoloji', 'Biyoloji ve Canlıların Ortak Özellikleri', 'TYT', 'Yaşam Bilimi Biyoloji', 1, 1),
  ('Biyoloji', 'Canlıların Temel Bileşenleri', 'TYT', 'Yaşam Bilimi Biyoloji', 1, 2),
  ('Biyoloji', 'Temel Bileşiklerin Canlılar için Önemi', 'TYT', 'Yaşam Bilimi Biyoloji', 1, 3),
  ('Biyoloji', 'Hücre Teorisi', 'TYT', 'Hücre', 2, 4),
  ('Biyoloji', 'Hücresel Yapılar ve Görevleri', 'TYT', 'Hücre', 2, 5),
  ('Biyoloji', 'Hücre Zarı ve Madde Geçişleri', 'TYT', 'Hücre', 2, 6),
  ('Biyoloji', 'Canlıların Çeşitliliği ve Sınıflandırılması', 'TYT', 'Canlılar Dünyası', 3, 7),
  ('Biyoloji', 'Canlı Alemleri ve Özellikleri', 'TYT', 'Canlılar Dünyası', 3, 8),
  ('Biyoloji', 'Canlıların Biyolojik ve Ekonomik Önemi', 'TYT', 'Canlılar Dünyası', 3, 9),
  ('Biyoloji', 'Virüsler', 'TYT', 'Canlılar Dünyası', 3, 10),
  ('Biyoloji', 'Hücre Bölünmelerine Giriş', 'TYT', 'Hücre Bölünmeleri', 4, 11),
  ('Biyoloji', 'Mitoz Bölünme', 'TYT', 'Hücre Bölünmeleri', 4, 12),
  ('Biyoloji', 'Eşeysiz Üreme', 'TYT', 'Hücre Bölünmeleri', 4, 13),
  ('Biyoloji', 'Mayoz Bölünme', 'TYT', 'Hücre Bölünmeleri', 4, 14),
  ('Biyoloji', 'Mitoz ve Mayoz Bölünmenin Karşılaştırılması', 'TYT', 'Hücre Bölünmeleri', 4, 15),
  ('Biyoloji', 'Eşeyli Üreme', 'TYT', 'Hücre Bölünmeleri', 4, 16),
  ('Biyoloji', 'Kalıtımın Genel İlkeleri', 'TYT', 'Kalıtım ve Biyolojik Çeşitlilik', 5, 17),
  ('Biyoloji', 'Genetik Varyasyon ve Biyoçeşitlilik', 'TYT', 'Kalıtım ve Biyolojik Çeşitlilik', 5, 18),
  ('Biyoloji', 'Ekosistem Ekolojisi', 'TYT', 'Ekosistem Ekolojisi ve Güncel Çevre Sorunları', 6, 19),
  ('Biyoloji', 'Güncel Çevre Sorunları', 'TYT', 'Ekosistem Ekolojisi ve Güncel Çevre Sorunları', 6, 20),
  ('Biyoloji', 'Sinir Sisteminin Yapı, Görev ve İşleyişi', 'AYT', 'Sinir Sistemi', 1, 1),
  ('Biyoloji', 'Sinir Sisteminin Sağlığı ve Hastalıkları', 'AYT', 'Sinir Sistemi', 1, 2),
  ('Biyoloji', 'İnsanda Endokrin Sistem', 'AYT', 'Endokrin Sistem', 2, 3),
  ('Biyoloji', 'Duyu Organlarının Yapısı ve İşleyişi', 'AYT', 'Duyu Organları', 3, 4),
  ('Biyoloji', 'Sinir Sistemi ve Duyu Organları Etkileşimi', 'AYT', 'Duyu Organları', 3, 5),
  ('Biyoloji', 'Duyu Organlarının Sağlığı ve Hastalıkları', 'AYT', 'Duyu Organları', 3, 6),
  ('Biyoloji', 'İskelet Sistemi', 'AYT', 'Destek ve Hareket Sistemi', 4, 7),
  ('Biyoloji', 'Kas Sistemi', 'AYT', 'Destek ve Hareket Sistemi', 4, 8),
  ('Biyoloji', 'Destek ve Hareket Sisteminin Sağlığı ve Hastalıkları', 'AYT', 'Destek ve Hareket Sistemi', 4, 9),
  ('Biyoloji', 'Sindirim Sistemi Organları', 'AYT', 'Sindirim Sistemi', 5, 10),
  ('Biyoloji', 'Besinlerin Kimyasal Sindirimi ve Emilimi', 'AYT', 'Sindirim Sistemi', 5, 11),
  ('Biyoloji', 'Sindirim Sisteminin Sağlığı ve Hastalıkları', 'AYT', 'Sindirim Sistemi', 5, 12),
  ('Biyoloji', 'Kan Dolaşımı', 'AYT', 'Dolaşım Sistemleri', 6, 13),
  ('Biyoloji', 'Lenf Dolaşımı', 'AYT', 'Dolaşım Sistemleri', 6, 14),
  ('Biyoloji', 'Dolaşım Sisteminin Sağlığı ve Hastalıkları', 'AYT', 'Dolaşım Sistemleri', 6, 15),
  ('Biyoloji', 'İnsanda Savunma ve Bağışıklık', 'AYT', 'Dolaşım Sistemleri', 6, 16),
  ('Biyoloji', 'Solunum Sistemine Giriş', 'AYT', 'Solunum Sistemi', 7, 17),
  ('Biyoloji', 'Soluk Alıp Verme Mekanizması', 'AYT', 'Solunum Sistemi', 7, 18),
  ('Biyoloji', 'Solunum Gazlarının Taşınması', 'AYT', 'Solunum Sistemi', 7, 19),
  ('Biyoloji', 'Solunum Sistemi Sağlığı ve Hastalıkları', 'AYT', 'Solunum Sistemi', 7, 20),
  ('Biyoloji', 'Üriner Sistem (Boşaltım Sistemi)', 'AYT', 'Üriner Sistem', 8, 21),
  ('Biyoloji', 'Üriner Sistem Sağlığı ve Hastalıkları', 'AYT', 'Üriner Sistem', 8, 22),
  ('Biyoloji', 'Üreme Sistemi', 'AYT', 'Üreme Sistemi ve Embriyonik Gelişim', 9, 23),
  ('Biyoloji', 'Üreme Sistemi Sağlığı ve Hastalıkları', 'AYT', 'Üreme Sistemi ve Embriyonik Gelişim', 9, 24),
  ('Biyoloji', 'İnsanda Embriyonik Gelişme', 'AYT', 'Üreme Sistemi ve Embriyonik Gelişim', 9, 25),
  ('Biyoloji', 'Komünite Ekolojisi', 'AYT', 'Komünite ve Popülasyon Ekolojisi', 10, 26),
  ('Biyoloji', 'Popülasyon Ekolojisi', 'AYT', 'Komünite ve Popülasyon Ekolojisi', 10, 27),
  ('Biyoloji', 'Nükleik Asitler', 'AYT', 'Genden Proteine', 11, 28),
  ('Biyoloji', 'DNA Replikasyonu', 'AYT', 'Genden Proteine', 11, 29),
  ('Biyoloji', 'Genetik Şifre ve Protein Sentezi', 'AYT', 'Genden Proteine', 11, 30),
  ('Biyoloji', 'Genetik Mühendisliği ve Biyoteknoloji', 'AYT', 'Genden Proteine', 11, 31),
  ('Biyoloji', 'Canlılık ve Enerji', 'AYT', 'Canlılarda Enerji Dönüşümleri', 12, 32),
  ('Biyoloji', 'Fotosentez', 'AYT', 'Canlılarda Enerji Dönüşümleri', 12, 33),
  ('Biyoloji', 'Kemosentez', 'AYT', 'Canlılarda Enerji Dönüşümleri', 12, 34),
  ('Biyoloji', 'Hücresel Solunum', 'AYT', 'Canlılarda Enerji Dönüşümleri', 12, 35),
  ('Biyoloji', 'Bitkisel Dokular', 'AYT', 'Bitki Biyolojisi', 13, 36),
  ('Biyoloji', 'Bitkisel Organlar', 'AYT', 'Bitki Biyolojisi', 13, 37),
  ('Biyoloji', 'Bitkisel Hormonlar ve Bitkilerde Hareket', 'AYT', 'Bitki Biyolojisi', 13, 38),
  ('Biyoloji', 'Bitkilerde Madde Taşınması', 'AYT', 'Bitki Biyolojisi', 13, 39),
  ('Biyoloji', 'Bitkilerde Eşeyli Üreme', 'AYT', 'Bitki Biyolojisi', 13, 40),
  ('Biyoloji', 'Canlılar ve Çevre Arasındaki İlişki', 'AYT', 'Canlılar ve Çevre', 14, 41),
  ('Matematik', 'Sayı Kümelerine Giriş', 'TYT', 'Sayı Kümeleri', 1, 1),
  ('Matematik', 'Doğal Sayılar', 'TYT', 'Sayı Kümeleri', 1, 2),
  ('Matematik', 'Tam Sayılar', 'TYT', 'Sayı Kümeleri', 1, 3),
  ('Matematik', 'Gerçek Sayılar', 'TYT', 'Sayı Kümeleri', 1, 4),
  ('Matematik', 'Tek ve Çift Sayılar', 'TYT', 'Sayı Kümeleri', 1, 5),
  ('Matematik', 'Ardışık Sayılar', 'TYT', 'Sayı Kümeleri', 1, 6),
  ('Matematik', 'Pozitif ve Negatif Sayılar', 'TYT', 'Sayı Kümeleri', 1, 7),
  ('Matematik', 'Asal Sayılar', 'TYT', 'Sayı Kümeleri', 1, 8),
  ('Matematik', 'Sayı Basamakları', 'TYT', 'Sayı Kümeleri', 1, 9),
  ('Matematik', 'Bölünebilme Kuralları', 'TYT', 'Bölme ve Bölünebilme Kuralları', 2, 10),
  ('Matematik', 'Basamak Kavramı', 'TYT', 'Bölme ve Bölünebilme Kuralları', 2, 11),
  ('Matematik', 'Basamak Çözümleme', 'TYT', 'Bölme ve Bölünebilme Kuralları', 2, 12),
  ('Matematik', 'En Büyük Ortak Bölen ve En Küçük Ortak Kat', 'TYT', 'EBOB - EKOK', 3, 13),
  ('Matematik', 'Periyodik Problemler', 'TYT', 'EBOB - EKOK', 3, 14),
  ('Matematik', 'Rasyonel Sayılar', 'TYT', 'Rasyonel Sayılar', 4, 15),
  ('Matematik', 'Aralık Kavramı', 'TYT', 'Basit Eşitsizlikler', 5, 16),
  ('Matematik', 'Birinci Dereceden İki Bilinmeyenli Denklemler', 'TYT', 'Basit Eşitsizlikler', 5, 17),
  ('Matematik', 'Mutlak Değer Kavramı', 'TYT', 'Mutlak Değer', 6, 18),
  ('Matematik', 'Mutlak Değerli Denklemler', 'TYT', 'Mutlak Değer', 6, 19),
  ('Matematik', 'Mutlak Değerli Eşitsizlikler', 'TYT', 'Mutlak Değer', 6, 20),
  ('Matematik', 'Tam Sayıların Tam Kuvvetleri', 'TYT', 'Üslü Sayılar', 7, 21),
  ('Matematik', 'Üslü Sayılarda Çarpma ve Bölme İşlemi', 'TYT', 'Üslü Sayılar', 7, 22),
  ('Matematik', 'Ondalık Sayıları Çözümleme', 'TYT', 'Üslü Sayılar', 7, 23),
  ('Matematik', '10''un Tam Sayı Kuvvetleri', 'TYT', 'Üslü Sayılar', 7, 24),
  ('Matematik', 'Bilimsel Gösterim', 'TYT', 'Üslü Sayılar', 7, 25),
  ('Matematik', 'Köklü Sayılarda İşlemler', 'TYT', 'Köklü Sayılar', 8, 26),
  ('Matematik', 'Çarpanlara Ayırma Kavramı', 'TYT', 'Çarpanlara Ayırma', 9, 27),
  ('Matematik', 'İki Kare Farkı Özdeşliği', 'TYT', 'Çarpanlara Ayırma', 9, 28),
  ('Matematik', 'Tam Kare Özdeşliği', 'TYT', 'Çarpanlara Ayırma', 9, 29),
  ('Matematik', 'Tam Küp Özdeşliği', 'TYT', 'Çarpanlara Ayırma', 9, 30),
  ('Matematik', 'Üç Terimli İfadenin Çarpanlara Ayrılması', 'TYT', 'Çarpanlara Ayırma', 9, 31),
  ('Matematik', 'Çarpanlara Ayırma Yöntemleri', 'TYT', 'Çarpanlara Ayırma', 9, 32),
  ('Matematik', 'Rasyonel İfadelerin Sadeleştirilmesi', 'TYT', 'Çarpanlara Ayırma', 9, 33),
  ('Matematik', 'Oran ve Orantı', 'TYT', 'Oran - Orantı', 10, 34),
  ('Matematik', 'Birinci Dereceden Bir Bilinmeyenli Denklemler', 'TYT', 'Denklem Çözme', 11, 35),
  ('Matematik', 'Denklem ve Eşitsizlik Sistemleri', 'TYT', 'Denklem Çözme', 11, 36),
  ('Matematik', 'Sayı Problemleri', 'TYT', 'Problemler', 12, 37),
  ('Matematik', 'Kesir Problemleri', 'TYT', 'Problemler', 12, 38),
  ('Matematik', 'Yaş Problemleri', 'TYT', 'Problemler', 12, 39),
  ('Matematik', 'Yüzde Problemleri', 'TYT', 'Problemler', 12, 40),
  ('Matematik', 'Kar - Zarar Problemleri', 'TYT', 'Problemler', 12, 41),
  ('Matematik', 'Karışım Problemleri', 'TYT', 'Problemler', 12, 42),
  ('Matematik', 'İşçi Problemleri', 'TYT', 'Problemler', 12, 43),
  ('Matematik', 'Hareket Problemleri', 'TYT', 'Problemler', 12, 44),
  ('Matematik', 'Grafik Problemleri', 'TYT', 'Problemler', 12, 45),
  ('Matematik', 'Sayısal Mantık', 'TYT', 'Problemler', 12, 46),
  ('Matematik', 'Kümelere Giriş', 'TYT', 'Kümeler', 13, 47),
  ('Matematik', 'Alt Kümeler ve Eşit Küme', 'TYT', 'Kümeler', 13, 48),
  ('Matematik', 'Kümelerde İşlemler', 'TYT', 'Kümeler', 13, 49),
  ('Matematik', 'Küme Problemleri', 'TYT', 'Kümeler', 13, 50),
  ('Matematik', 'Sıralı İkili ve Kartezyen Çarpım', 'TYT', 'Kümeler', 13, 51),
  ('Matematik', 'Önermeler', 'TYT', 'Mantık', 14, 52),
  ('Matematik', 'Bileşik Önermeler', 'TYT', 'Mantık', 14, 53),
  ('Matematik', 'Niceleyiciler', 'TYT', 'Mantık', 14, 54),
  ('Matematik', 'İspat Kavramları ve Yöntemleri', 'TYT', 'Mantık', 14, 55),
  ('Matematik', 'Fonksiyon Kavramı', 'TYT', 'Fonksiyonlar', 15, 56),
  ('Matematik', 'Fonksiyon Çeşitleri', 'TYT', 'Fonksiyonlar', 15, 57),
  ('Matematik', 'Fonksiyonun Grafiği', 'TYT', 'Fonksiyonlar', 15, 58),
  ('Matematik', 'Doğrusal Fonksiyon', 'TYT', 'Fonksiyonlar', 15, 59),
  ('Matematik', 'Birebir Fonksiyon ve Örten Fonksiyon', 'TYT', 'Fonksiyonlar', 15, 60),
  ('Matematik', 'Sabit, Sıfır ve Birim Fonksiyon', 'TYT', 'Fonksiyonlar', 15, 61),
  ('Matematik', 'Bileşke Fonksiyon', 'TYT', 'Fonksiyonlar', 15, 62),
  ('Matematik', 'Ters Fonksiyon', 'TYT', 'Fonksiyonlar', 15, 63),
  ('Matematik', 'Polinom Kavramı', 'TYT', 'Polinomlar', 16, 64),
  ('Matematik', 'Polinomlarda İşlemler', 'TYT', 'Polinomlar', 16, 65),
  ('Matematik', 'İkinci Dereceden Bir Bilinmeyenli Denklem', 'TYT', 'İkinci Dereceden Denklemler', 17, 66),
  ('Matematik', 'Karmaşık Sayılar', 'TYT', 'İkinci Dereceden Denklemler', 17, 67),
  ('Matematik', 'Sayma', 'TYT', 'Sayma ve Olasılık', 18, 68),
  ('Matematik', 'Permütasyon', 'TYT', 'Sayma ve Olasılık', 18, 69),
  ('Matematik', 'Tekrarlı Permütasyon', 'TYT', 'Sayma ve Olasılık', 18, 70),
  ('Matematik', 'Kombinasyon', 'TYT', 'Sayma ve Olasılık', 18, 71),
  ('Matematik', 'Binom Açılımı', 'TYT', 'Sayma ve Olasılık', 18, 72),
  ('Matematik', 'Pascal Üçgeni', 'TYT', 'Sayma ve Olasılık', 18, 73),
  ('Matematik', 'Olasılık', 'TYT', 'Sayma ve Olasılık', 18, 74),
  ('Matematik', 'Veri Toplama', 'TYT', 'İstatistiksel Araştırma Süreci', 19, 75),
  ('Matematik', 'Veri Analizi Yapma ve Sonuçları Yorumlama', 'TYT', 'İstatistiksel Araştırma Süreci', 19, 76),
  ('Matematik', 'Merkezi Eğilim ve Yayılım Ölçüleri', 'TYT', 'İstatistiksel Araştırma Süreci', 19, 77),
  ('Matematik', 'Histogram', 'TYT', 'İstatistiksel Araştırma Süreci', 19, 78),
  ('Matematik', 'Çizgi, Sütun ve Daire Grafiği', 'TYT', 'İstatistiksel Araştırma Süreci', 19, 79),
  ('Matematik', 'Açı Kavramı', 'AYT', 'Trigonometri', 1, 1),
  ('Matematik', 'Açı Ölçü Birimleri ve Esas Ölçü', 'AYT', 'Trigonometri', 1, 2),
  ('Matematik', 'Trigonometrik Fonksiyonlar', 'AYT', 'Trigonometri', 1, 3),
  ('Matematik', 'Kosinüs Teoremi', 'AYT', 'Trigonometri', 1, 4),
  ('Matematik', 'Sinüs Teoremi', 'AYT', 'Trigonometri', 1, 5),
  ('Matematik', 'Trigonometrik Fonksiyonların Grafikleri', 'AYT', 'Trigonometri', 1, 6),
  ('Matematik', 'Ters Trigonometrik Fonksiyonlar', 'AYT', 'Trigonometri', 1, 7),
  ('Matematik', 'Toplam-Fark Formülleri', 'AYT', 'Trigonometri', 1, 8),
  ('Matematik', 'Yarım Açı Formülleri', 'AYT', 'Trigonometri', 1, 9),
  ('Matematik', 'Trigonometrik Denklemler', 'AYT', 'Trigonometri', 1, 10),
  ('Matematik', 'Fonksiyonların Dönüşümleri', 'AYT', 'Fonksiyonlarda Uygulamalar', 2, 11),
  ('Matematik', 'Fonksiyonlarla İlgili Uygulamalar', 'AYT', 'Fonksiyonlarda Uygulamalar', 2, 12),
  ('Matematik', 'Parabol', 'AYT', 'Fonksiyonlarda Uygulamalar', 2, 13),
  ('Matematik', 'İkinci Dereceden İki Bilinmeyenli Denklemler', 'AYT', 'Denklem ve Eşitsizlik Sistemleri', 3, 14),
  ('Matematik', 'İkinci Dereceden Bir Bilinmeyenli Eşitsizlikler ve Eşitsizlik Sistemleri', 'AYT', 'Denklem ve Eşitsizlik Sistemleri', 3, 15),
  ('Matematik', 'Koşullu Olasılık', 'AYT', 'Olasılık', 4, 16),
  ('Matematik', 'Bağımlı ve Bağımsız Olaylar', 'AYT', 'Olasılık', 4, 17),
  ('Matematik', 'Bileşik Olaylar', 'AYT', 'Olasılık', 4, 18),
  ('Matematik', 'Deneysel ve Teorik Olasılık', 'AYT', 'Olasılık', 4, 19),
  ('Matematik', 'Üstel Fonksiyon', 'AYT', 'Üstel ve Logaritmik Fonksiyonlar', 5, 20),
  ('Matematik', 'Logaritmaya Giriş', 'AYT', 'Üstel ve Logaritmik Fonksiyonlar', 5, 21),
  ('Matematik', 'Doğal Logaritma', 'AYT', 'Üstel ve Logaritmik Fonksiyonlar', 5, 22),
  ('Matematik', 'Logaritmanın Özellikleri', 'AYT', 'Üstel ve Logaritmik Fonksiyonlar', 5, 23),
  ('Matematik', 'Üstel ve Logaritmik Denklemler', 'AYT', 'Üstel ve Logaritmik Fonksiyonlar', 5, 24),
  ('Matematik', 'Üstel ve Logaritmik Eşitsizlikler', 'AYT', 'Üstel ve Logaritmik Fonksiyonlar', 5, 25),
  ('Matematik', 'Dizilere Giriş', 'AYT', 'Diziler', 6, 26),
  ('Matematik', 'Aritmetik Dizi', 'AYT', 'Diziler', 6, 27),
  ('Matematik', 'Geometrik Dizi', 'AYT', 'Diziler', 6, 28),
  ('Matematik', 'Sağdan ve Soldan Limit', 'AYT', 'Limit ve Süreklilik', 7, 29),
  ('Matematik', 'Limitte Grafik Yorumu', 'AYT', 'Limit ve Süreklilik', 7, 30),
  ('Matematik', 'Limit Özellikleri', 'AYT', 'Limit ve Süreklilik', 7, 31),
  ('Matematik', 'Özel Tanımlı Fonksiyonlarda Limit', 'AYT', 'Limit ve Süreklilik', 7, 32),
  ('Matematik', 'Limitte Belirsizlik', 'AYT', 'Limit ve Süreklilik', 7, 33),
  ('Matematik', 'Limitte Süreklilik', 'AYT', 'Limit ve Süreklilik', 7, 34),
  ('Matematik', 'Türevin Tanımı', 'AYT', 'Türev', 8, 35),
  ('Matematik', 'Türev Alma Kuralları', 'AYT', 'Türev', 8, 36),
  ('Matematik', 'Çarpımın ve Bölümün Türevi', 'AYT', 'Türev', 8, 37),
  ('Matematik', 'Bileşke Fonksiyonun Türevi ve Zincir Kuralı', 'AYT', 'Türev', 8, 38),
  ('Matematik', 'Parçalı ve Mutlak Değer Fonksiyonun Türevi', 'AYT', 'Türev', 8, 39),
  ('Matematik', 'Türev - Süreklilik İlişkisi', 'AYT', 'Türev', 8, 40),
  ('Matematik', 'Türevin Geometrik Yorumu', 'AYT', 'Türev', 8, 41),
  ('Matematik', 'Artan ve Azalan Fonksiyonlar', 'AYT', 'Türev', 8, 42),
  ('Matematik', 'Ekstremum Noktalar', 'AYT', 'Türev', 8, 43),
  ('Matematik', 'Maksimum Minimum Problemleri', 'AYT', 'Türev', 8, 44),
  ('Matematik', 'Polinom Fonksiyon Grafikleri', 'AYT', 'Türev', 8, 45),
  ('Matematik', 'Belirsiz İntegral', 'AYT', 'İntegral', 9, 46),
  ('Matematik', 'İntegral Alma Kuralları', 'AYT', 'İntegral', 9, 47),
  ('Matematik', 'Değişken Değiştirme', 'AYT', 'İntegral', 9, 48),
  ('Matematik', 'Belirli İntegral', 'AYT', 'İntegral', 9, 49),
  ('Matematik', 'Belirli İntegralde Değişken Değiştirme', 'AYT', 'İntegral', 9, 50),
  ('Matematik', 'Tek ve Çift Fonksiyonların İntegrali', 'AYT', 'İntegral', 9, 51),
  ('Matematik', 'Parçalı ve Mutlak Değer Fonksiyonun İntegralleri', 'AYT', 'İntegral', 9, 52),
  ('Matematik', 'İntegralde Alan Hesabı', 'AYT', 'İntegral', 9, 53),
  ('Matematik', 'Riemann Toplamı', 'AYT', 'İntegral', 9, 54),
  ('Matematik', 'Üçgenler ve Özellikleri', 'TYT', 'Üçgenler', 20, 80),
  ('Matematik', 'Üçgende Açılar', 'TYT', 'Üçgenler', 20, 81),
  ('Matematik', 'Özel Üçgenler', 'TYT', 'Üçgenler', 20, 82),
  ('Matematik', 'Açıortay', 'TYT', 'Üçgenler', 20, 83),
  ('Matematik', 'Kenarortay', 'TYT', 'Üçgenler', 20, 84),
  ('Matematik', 'Açı Kenar Bağıntıları', 'TYT', 'Üçgenler', 20, 85),
  ('Matematik', 'Pisagor Bağıntısı', 'TYT', 'Üçgenler', 20, 86),
  ('Matematik', 'Eşlik ve Benzerlik', 'TYT', 'Üçgenler', 20, 87),
  ('Matematik', 'Üçgende Alan', 'TYT', 'Üçgenler', 20, 88),
  ('Matematik', 'Çokgenler', 'TYT', 'Dörtgenler ve Çokgenler', 21, 89),
  ('Matematik', 'Dörtgenler', 'TYT', 'Dörtgenler ve Çokgenler', 21, 90),
  ('Matematik', 'Yamuk', 'TYT', 'Dörtgenler ve Çokgenler', 21, 91),
  ('Matematik', 'Paralelkenar', 'TYT', 'Dörtgenler ve Çokgenler', 21, 92),
  ('Matematik', 'Eşkenar Dörtgen', 'TYT', 'Dörtgenler ve Çokgenler', 21, 93),
  ('Matematik', 'Dikdörtgen', 'TYT', 'Dörtgenler ve Çokgenler', 21, 94),
  ('Matematik', 'Kare', 'TYT', 'Dörtgenler ve Çokgenler', 21, 95),
  ('Matematik', 'Deltoid', 'TYT', 'Dörtgenler ve Çokgenler', 21, 96),
  ('Matematik', 'Çemberin Temel Elemanları', 'TYT', 'Çember ve Daire', 22, 97),
  ('Matematik', 'Çemberde Açılar', 'TYT', 'Çember ve Daire', 22, 98),
  ('Matematik', 'Çemberde Teğet', 'TYT', 'Çember ve Daire', 22, 99),
  ('Matematik', 'Dairenin Çevresi ve Alanı', 'TYT', 'Çember ve Daire', 22, 100),
  ('Matematik', 'Dik Prizmalar', 'TYT', 'Katı Cisimler', 23, 101),
  ('Matematik', 'Dik Piramit', 'TYT', 'Katı Cisimler', 23, 102),
  ('Matematik', 'Dik Dairesel Silindir', 'TYT', 'Katı Cisimler', 23, 103),
  ('Matematik', 'Dik Koni', 'TYT', 'Katı Cisimler', 23, 104),
  ('Matematik', 'Küre', 'TYT', 'Katı Cisimler', 23, 105),
  ('Matematik', 'Noktanın Analitik İncelenmesi', 'TYT', 'Analitik Geometri', 24, 106),
  ('Matematik', 'Doğrunun Analitik İncelenmesi', 'TYT', 'Analitik Geometri', 24, 107),
  ('Matematik', 'Çemberin Analitik İncelenmesi', 'TYT', 'Analitik Geometri', 24, 108),
  ('Matematik', 'Dönüşüm Geometrisi', 'TYT', 'Dönüşümler', 25, 109),
  ('Matematik', 'Üçgenler ve Özellikleri', 'AYT', 'Üçgenler', 10, 55),
  ('Matematik', 'Üçgende Açılar', 'AYT', 'Üçgenler', 10, 56),
  ('Matematik', 'Özel Üçgenler', 'AYT', 'Üçgenler', 10, 57),
  ('Matematik', 'Açıortay', 'AYT', 'Üçgenler', 10, 58),
  ('Matematik', 'Kenarortay', 'AYT', 'Üçgenler', 10, 59),
  ('Matematik', 'Açı Kenar Bağıntıları', 'AYT', 'Üçgenler', 10, 60),
  ('Matematik', 'Pisagor Bağıntısı', 'AYT', 'Üçgenler', 10, 61),
  ('Matematik', 'Eşlik ve Benzerlik', 'AYT', 'Üçgenler', 10, 62),
  ('Matematik', 'Üçgende Alan', 'AYT', 'Üçgenler', 10, 63),
  ('Matematik', 'Çokgenler', 'AYT', 'Dörtgenler ve Çokgenler', 11, 64),
  ('Matematik', 'Dörtgenler', 'AYT', 'Dörtgenler ve Çokgenler', 11, 65),
  ('Matematik', 'Yamuk', 'AYT', 'Dörtgenler ve Çokgenler', 11, 66),
  ('Matematik', 'Paralelkenar', 'AYT', 'Dörtgenler ve Çokgenler', 11, 67),
  ('Matematik', 'Eşkenar Dörtgen', 'AYT', 'Dörtgenler ve Çokgenler', 11, 68),
  ('Matematik', 'Dikdörtgen', 'AYT', 'Dörtgenler ve Çokgenler', 11, 69),
  ('Matematik', 'Kare', 'AYT', 'Dörtgenler ve Çokgenler', 11, 70),
  ('Matematik', 'Deltoid', 'AYT', 'Dörtgenler ve Çokgenler', 11, 71),
  ('Matematik', 'Çemberin Temel Elemanları', 'AYT', 'Çember ve Daire', 12, 72),
  ('Matematik', 'Çemberde Açılar', 'AYT', 'Çember ve Daire', 12, 73),
  ('Matematik', 'Çemberde Teğet', 'AYT', 'Çember ve Daire', 12, 74),
  ('Matematik', 'Dairenin Çevresi ve Alanı', 'AYT', 'Çember ve Daire', 12, 75),
  ('Matematik', 'Dik Prizmalar', 'AYT', 'Katı Cisimler', 13, 76),
  ('Matematik', 'Dik Piramit', 'AYT', 'Katı Cisimler', 13, 77),
  ('Matematik', 'Dik Dairesel Silindir', 'AYT', 'Katı Cisimler', 13, 78),
  ('Matematik', 'Dik Koni', 'AYT', 'Katı Cisimler', 13, 79),
  ('Matematik', 'Küre', 'AYT', 'Katı Cisimler', 13, 80),
  ('Matematik', 'Noktanın Analitik İncelenmesi', 'AYT', 'Analitik Geometri', 14, 81),
  ('Matematik', 'Doğrunun Analitik İncelenmesi', 'AYT', 'Analitik Geometri', 14, 82),
  ('Matematik', 'Çemberin Analitik İncelenmesi', 'AYT', 'Analitik Geometri', 14, 83),
  ('Matematik', 'Dönüşüm Geometrisi', 'AYT', 'Dönüşümler', 15, 84),
  ('Türkçe', 'Anlam Bakımından Sözcükler', 'TYT', 'Sözcükte Anlam', 1, 1),
  ('Türkçe', 'Anlam İlişkisi Bakımından Sözcükler', 'TYT', 'Sözcükte Anlam', 1, 2),
  ('Türkçe', 'Anlatımlarına Göre Cümleler', 'TYT', 'Cümlede Anlam', 2, 3),
  ('Türkçe', 'Cümle Yorumu', 'TYT', 'Cümlede Anlam', 2, 4),
  ('Türkçe', 'Cümlede Anlam İlişkileri', 'TYT', 'Cümlede Anlam', 2, 5),
  ('Türkçe', 'Düşünceyi Geliştirme Yolları', 'TYT', 'Paragrafta Anlam', 3, 6),
  ('Türkçe', 'Anlatım Biçimleri', 'TYT', 'Paragrafta Anlam', 3, 7),
  ('Türkçe', 'Paragrafta Konu, Ana Düşünce ve Yardımcı Düşünceler', 'TYT', 'Paragrafta Anlam', 3, 8),
  ('Türkçe', 'Paragrafta Yapı', 'TYT', 'Paragrafta Anlam', 3, 9),
  ('Türkçe', 'İyi Bir Anlatımda Bulunması Gereken Özellikler', 'TYT', 'Paragrafta Anlam', 3, 10),
  ('Türkçe', 'Ses Bilgisine Giriş', 'TYT', 'Ses Bilgisi', 4, 11),
  ('Türkçe', 'Büyük ve Küçük Ünlü Uyumu', 'TYT', 'Ses Bilgisi', 4, 12),
  ('Türkçe', 'Ünlü Düşmesi ve Ünlü Türemesi', 'TYT', 'Ses Bilgisi', 4, 13),
  ('Türkçe', 'Ünlü Değişimi ve Ünsüz Yumuşaması', 'TYT', 'Ses Bilgisi', 4, 14),
  ('Türkçe', 'Ünsüz Düşmesi ve Ünlü Daralması', 'TYT', 'Ses Bilgisi', 4, 15),
  ('Türkçe', 'Ulama ve Kaynaştırma Ünsüzü', 'TYT', 'Ses Bilgisi', 4, 16),
  ('Türkçe', 'Ünsüz Türemesi ve Ünsüz Benzeşmesi', 'TYT', 'Ses Bilgisi', 4, 17),
  ('Türkçe', 'Kök', 'TYT', 'Sözcükte Yapı', 5, 18),
  ('Türkçe', 'Ek', 'TYT', 'Sözcükte Yapı', 5, 19),
  ('Türkçe', 'Gövde', 'TYT', 'Sözcükte Yapı', 5, 20),
  ('Türkçe', 'Yapı Bakımından Kelimeler', 'TYT', 'Sözcükte Yapı', 5, 21),
  ('Türkçe', 'İsim', 'TYT', 'Sözcük Türleri', 6, 22),
  ('Türkçe', 'Sıfat', 'TYT', 'Sözcük Türleri', 6, 23),
  ('Türkçe', 'Zamir', 'TYT', 'Sözcük Türleri', 6, 24),
  ('Türkçe', 'Zarf', 'TYT', 'Sözcük Türleri', 6, 25),
  ('Türkçe', 'Fiiller', 'TYT', 'Sözcük Türleri', 6, 26),
  ('Türkçe', 'Edat', 'TYT', 'Sözcük Türleri', 6, 27),
  ('Türkçe', 'Bağlaç ve Ünlem', 'TYT', 'Sözcük Türleri', 6, 28),
  ('Türkçe', 'İsim Fiiller', 'TYT', 'Fiilimsi', 7, 29),
  ('Türkçe', 'Sıfat Fiiller', 'TYT', 'Fiilimsi', 7, 30),
  ('Türkçe', 'Zarf Fiiller', 'TYT', 'Fiilimsi', 7, 31),
  ('Türkçe', 'İsim Tamlamaları', 'TYT', 'Tamlamalar', 8, 32),
  ('Türkçe', 'Sıfat Tamlamaları', 'TYT', 'Tamlamalar', 8, 33),
  ('Türkçe', 'Cümlenin Temel Öğeleri', 'TYT', 'Cümlenin Ögeleri', 9, 34),
  ('Türkçe', 'Cümlenin Yardımcı Öğeleri', 'TYT', 'Cümlenin Ögeleri', 9, 35),
  ('Türkçe', 'Özne-Yüklem İlişkisi', 'TYT', 'Fiilde Çatı', 10, 36),
  ('Türkçe', 'Nesne-Yüklem İlişkisi', 'TYT', 'Fiilde Çatı', 10, 37),
  ('Türkçe', 'Yüklemin Türüne Göre Cümleler', 'TYT', 'Cümle Çeşitleri', 11, 38),
  ('Türkçe', 'Yüklemin Yerine Göre Cümleler', 'TYT', 'Cümle Çeşitleri', 11, 39),
  ('Türkçe', 'Anlamına Göre Cümleler', 'TYT', 'Cümle Çeşitleri', 11, 40),
  ('Türkçe', 'Yapısına Göre Cümleler', 'TYT', 'Cümle Çeşitleri', 11, 41),
  ('Türkçe', 'Anlam Düzeyinde Anlatım Bozuklukları', 'TYT', 'Anlatım Bozukluğu', 12, 42),
  ('Türkçe', 'Dil Bilgisi Düzeyinde Anlatım Bozuklukları', 'TYT', 'Anlatım Bozukluğu', 12, 43),
  ('Türkçe', 'Noktalama İşaretleri', 'TYT', 'Yazım Kuralları ve Noktalama İşaretleri', 13, 44),
  ('Türkçe', 'Yazım Kuralları', 'TYT', 'Yazım Kuralları ve Noktalama İşaretleri', 13, 45),
  ('Tarih', 'Tarih Bilimi', 'TYT', 'Tarih ve Zaman', 1, 1),
  ('Tarih', 'Zaman ve Takvim', 'TYT', 'Tarih ve Zaman', 1, 2),
  ('Tarih', 'İnsanlığa Ait İzler', 'TYT', 'İnsanlığın İlk Dönemleri', 2, 3),
  ('Tarih', 'Yazının İcadı ve Önemi', 'TYT', 'İnsanlığın İlk Dönemleri', 2, 4),
  ('Tarih', 'İlk Çağ Uygarlıkları', 'TYT', 'İnsanlığın İlk Dönemleri', 2, 5),
  ('Tarih', 'Orta Çağ''da Siyasi Yapılar', 'TYT', 'Orta Çağ''da Dünya', 3, 6),
  ('Tarih', 'Orta Çağ''da Tarım ve Ticaret', 'TYT', 'Orta Çağ''da Dünya', 3, 7),
  ('Tarih', 'Orta Çağ''da Ordu ve Kanunlar', 'TYT', 'Orta Çağ''da Dünya', 3, 8),
  ('Tarih', 'İlk Türk Devletleri', 'TYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 9),
  ('Tarih', 'Kavimler Göçü ve Avrupa Hun Devleti', 'TYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 10),
  ('Tarih', 'Diğer Türk Devletleri ve Toplulukları', 'TYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 11),
  ('Tarih', 'İslamiyet Öncesi Türk Kültür ve Uygarlığı', 'TYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 12),
  ('Tarih', 'İslamiyet''in Doğuşu', 'TYT', 'İslam Medeniyetinin Doğuşu', 5, 13),
  ('Tarih', 'Dört Halife Dönemi', 'TYT', 'İslam Medeniyetinin Doğuşu', 5, 14),
  ('Tarih', 'Emeviler Dönemi', 'TYT', 'İslam Medeniyetinin Doğuşu', 5, 15),
  ('Tarih', 'Abbasiler ve Mısır''da Kurulan Türk İslam Devletleri', 'TYT', 'İslam Medeniyetinin Doğuşu', 5, 16),
  ('Tarih', 'Türklerin İslamiyet''i Kabulü', 'TYT', 'Türklerin İslamiyet''i Kabulü ve İlk Türk İslam Devletleri', 6, 17),
  ('Tarih', 'Karahanlılar ve Gazneliler', 'TYT', 'Türklerin İslamiyet''i Kabulü ve İlk Türk İslam Devletleri', 6, 18),
  ('Tarih', 'Büyük Selçuklu Devleti', 'TYT', 'Türklerin İslamiyet''i Kabulü ve İlk Türk İslam Devletleri', 6, 19),
  ('Tarih', 'İslamiyet''in Türk Devlet ve Toplum Yapısına Etkisi', 'TYT', 'Türklerin İslamiyet''i Kabulü ve İlk Türk İslam Devletleri', 6, 20),
  ('Tarih', 'Oğuz Göçleri ve Anadolu', 'TYT', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 7, 21),
  ('Tarih', 'Haçlı Seferleri', 'TYT', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 7, 22),
  ('Tarih', 'Anadolu''da Kurulan İlk Türk Beylikleri', 'TYT', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 7, 23),
  ('Tarih', 'Türkiye Selçuklu Devleti', 'TYT', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 7, 24),
  ('Tarih', 'Beylikten Devlete Osmanlı Siyaseti', 'TYT', 'Beylikten Devlete Osmanlı Siyaseti (1302-1453)', 8, 25),
  ('Tarih', 'Osmanlı Padişahları', 'TYT', 'Beylikten Devlete Osmanlı Siyaseti (1302-1453)', 8, 26),
  ('Tarih', 'Fatih Sultan Mehmet Dönemi', 'TYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 27),
  ('Tarih', 'II. Bayezid Dönemi', 'TYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 28),
  ('Tarih', 'Yavuz Sultan Selim Dönemi', 'TYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 29),
  ('Tarih', 'Kanuni Sultan Süleyman Dönemi', 'TYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 30),
  ('Tarih', 'Sokullu Mehmet Paşa Dönemi', 'TYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 31),
  ('Tarih', 'Osmanlı Kültür ve Medeniyeti', 'TYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 32),
  ('Tarih', 'Osmanlı Devleti Duraklama Dönemi', 'TYT', 'Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti', 10, 33),
  ('Tarih', '17. Yüzyıl Islahatları ve İsyanları', 'TYT', 'Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti', 10, 34),
  ('Tarih', 'Osmanlı Devleti Gerileme Dönemi', 'TYT', 'Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti', 10, 35),
  ('Tarih', 'Yeni Çağ Avrupa', 'TYT', 'Yeni ve Yakın Çağda Avrupa', 11, 36),
  ('Tarih', 'Avrupa''da Değişim Çağı', 'TYT', 'Yeni ve Yakın Çağda Avrupa', 11, 37),
  ('Tarih', 'Osmanlı Devleti''nde Değişim', 'TYT', 'Yeni ve Yakın Çağda Avrupa', 11, 38),
  ('Tarih', 'Yakın Çağ Avrupa', 'TYT', 'Yeni ve Yakın Çağda Avrupa', 11, 39),
  ('Tarih', 'II. Mahmut Dönemi', 'TYT', 'Uluslararası İlişkilerde Denge Stratejisi', 12, 40),
  ('Tarih', 'Abdülmecid Dönemi', 'TYT', 'Uluslararası İlişkilerde Denge Stratejisi', 12, 41),
  ('Tarih', 'Abdülaziz Dönemi', 'TYT', 'Uluslararası İlişkilerde Denge Stratejisi', 12, 42),
  ('Tarih', 'II. Abdülhamid Dönemi', 'TYT', 'Uluslararası İlişkilerde Denge Stratejisi', 12, 43),
  ('Tarih', 'Mustafa Kemal''in Hayatı', 'TYT', '20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya', 13, 44),
  ('Tarih', 'I. Dünya Savaşı ve Osmanlı', 'TYT', '20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya', 13, 45),
  ('Tarih', 'Dünya Savaşı Sona Ererken', 'TYT', '20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya', 13, 46),
  ('Tarih', 'Kurtuluş Savaşı Hazırlık Dönemi', 'TYT', 'Milli Mücadele', 14, 47),
  ('Tarih', 'Kurtuluş Savaşı Cepheler', 'TYT', 'Milli Mücadele', 14, 48),
  ('Tarih', 'Mudanya ve Lozan Antlaşmaları', 'TYT', 'Milli Mücadele', 14, 49),
  ('Tarih', 'Atatürk İlkeleri', 'TYT', 'Atatürkçülük ve Türk İnkılabı', 15, 50),
  ('Tarih', 'Atatürk Dönemi İç Politikası', 'TYT', 'Atatürkçülük ve Türk İnkılabı', 15, 51),
  ('Tarih', 'Tarih Bilimi', 'AYT', 'Tarih ve Zaman', 1, 1),
  ('Tarih', 'Zaman ve Takvim', 'AYT', 'Tarih ve Zaman', 1, 2),
  ('Tarih', 'İnsanlığa Ait İzler', 'AYT', 'İnsanlığın İlk Dönemleri', 2, 3),
  ('Tarih', 'Yazının İcadı ve Önemi', 'AYT', 'İnsanlığın İlk Dönemleri', 2, 4),
  ('Tarih', 'İlk Çağ Uygarlıkları', 'AYT', 'İnsanlığın İlk Dönemleri', 2, 5),
  ('Tarih', 'Orta Çağ''da Siyasi Yapılar', 'AYT', 'Orta Çağ''da Dünya', 3, 6),
  ('Tarih', 'Orta Çağ''da Tarım ve Ticaret', 'AYT', 'Orta Çağ''da Dünya', 3, 7),
  ('Tarih', 'Orta Çağ''da Ordu ve Kanunlar', 'AYT', 'Orta Çağ''da Dünya', 3, 8),
  ('Tarih', 'İlk Türk Devletleri', 'AYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 9),
  ('Tarih', 'Kavimler Göçü ve Avrupa Hun Devleti', 'AYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 10),
  ('Tarih', 'Diğer Türk Devletleri ve Toplulukları', 'AYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 11),
  ('Tarih', 'İslamiyet Öncesi Türk Kültür ve Uygarlığı', 'AYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 12),
  ('Tarih', 'İslamiyet''in Doğuşu', 'AYT', 'İslam Medeniyetinin Doğuşu', 5, 13),
  ('Tarih', 'Dört Halife Dönemi', 'AYT', 'İslam Medeniyetinin Doğuşu', 5, 14),
  ('Tarih', 'Emeviler Dönemi', 'AYT', 'İslam Medeniyetinin Doğuşu', 5, 15),
  ('Tarih', 'Abbasiler ve Mısır''da Kurulan Türk İslam Devletleri', 'AYT', 'İslam Medeniyetinin Doğuşu', 5, 16),
  ('Tarih', 'Türklerin İslamiyet''i Kabulü', 'AYT', 'Türklerin İslamiyet''i Kabulü ve İlk Türk İslam Devletleri', 6, 17),
  ('Tarih', 'Karahanlılar ve Gazneliler', 'AYT', 'Türklerin İslamiyet''i Kabulü ve İlk Türk İslam Devletleri', 6, 18),
  ('Tarih', 'Büyük Selçuklu Devleti', 'AYT', 'Türklerin İslamiyet''i Kabulü ve İlk Türk İslam Devletleri', 6, 19),
  ('Tarih', 'İslamiyet''in Türk Devlet ve Toplum Yapısına Etkisi', 'AYT', 'Türklerin İslamiyet''i Kabulü ve İlk Türk İslam Devletleri', 6, 20),
  ('Tarih', 'Oğuz Göçleri ve Anadolu', 'AYT', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 7, 21),
  ('Tarih', 'Haçlı Seferleri', 'AYT', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 7, 22),
  ('Tarih', 'Anadolu''da Kurulan İlk Türk Beylikleri', 'AYT', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 7, 23),
  ('Tarih', 'Türkiye Selçuklu Devleti', 'AYT', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 7, 24),
  ('Tarih', 'Beylikten Devlete Osmanlı Siyaseti', 'AYT', 'Beylikten Devlete Osmanlı Siyaseti (1302-1453)', 8, 25),
  ('Tarih', 'Osmanlı Padişahları', 'AYT', 'Beylikten Devlete Osmanlı Siyaseti (1302-1453)', 8, 26),
  ('Tarih', 'Fatih Sultan Mehmet Dönemi', 'AYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 27),
  ('Tarih', 'II. Bayezid Dönemi', 'AYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 28),
  ('Tarih', 'Yavuz Sultan Selim Dönemi', 'AYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 29),
  ('Tarih', 'Kanuni Sultan Süleyman Dönemi', 'AYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 30),
  ('Tarih', 'Sokullu Mehmet Paşa Dönemi', 'AYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 31),
  ('Tarih', 'Osmanlı Kültür ve Medeniyeti', 'AYT', 'Dünya Gücü Osmanlı (1453-1595)', 9, 32),
  ('Tarih', 'Osmanlı Devleti Duraklama Dönemi', 'AYT', 'Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti', 10, 33),
  ('Tarih', '17. Yüzyıl Islahatları ve İsyanları', 'AYT', 'Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti', 10, 34),
  ('Tarih', 'Osmanlı Devleti Gerileme Dönemi', 'AYT', 'Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti', 10, 35),
  ('Tarih', 'Yeni Çağ Avrupa', 'AYT', 'Yeni ve Yakın Çağda Avrupa', 11, 36),
  ('Tarih', 'Avrupa''da Değişim Çağı', 'AYT', 'Yeni ve Yakın Çağda Avrupa', 11, 37),
  ('Tarih', 'Osmanlı Devleti''nde Değişim', 'AYT', 'Yeni ve Yakın Çağda Avrupa', 11, 38),
  ('Tarih', 'Yakın Çağ Avrupa', 'AYT', 'Yeni ve Yakın Çağda Avrupa', 11, 39),
  ('Tarih', 'II. Mahmut Dönemi', 'AYT', 'Uluslararası İlişkilerde Denge Stratejisi', 12, 40),
  ('Tarih', 'Abdülmecid Dönemi', 'AYT', 'Uluslararası İlişkilerde Denge Stratejisi', 12, 41),
  ('Tarih', 'Abdülaziz Dönemi', 'AYT', 'Uluslararası İlişkilerde Denge Stratejisi', 12, 42),
  ('Tarih', 'II. Abdülhamid Dönemi', 'AYT', 'Uluslararası İlişkilerde Denge Stratejisi', 12, 43),
  ('Tarih', 'Mustafa Kemal''in Hayatı', 'AYT', '20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya', 13, 44),
  ('Tarih', 'I. Dünya Savaşı ve Osmanlı', 'AYT', '20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya', 13, 45),
  ('Tarih', 'Dünya Savaşı Sona Ererken', 'AYT', '20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya', 13, 46),
  ('Tarih', 'Kurtuluş Savaşı Hazırlık Dönemi', 'AYT', 'Milli Mücadele', 14, 47),
  ('Tarih', 'Kurtuluş Savaşı Cepheler', 'AYT', 'Milli Mücadele', 14, 48),
  ('Tarih', 'Mudanya ve Lozan Antlaşmaları', 'AYT', 'Milli Mücadele', 14, 49),
  ('Tarih', 'Atatürk İlkeleri', 'AYT', 'Atatürkçülük ve Türk İnkılabı', 15, 50),
  ('Tarih', 'Atatürk Dönemi İç Politikası', 'AYT', 'Atatürkçülük ve Türk İnkılabı', 15, 51),
  ('Coğrafya', 'Doğa ve İnsan Etkileşimi', 'TYT', 'Doğal Sistemler', 1, 1),
  ('Coğrafya', 'Bir Bilim Olarak Coğrafya', 'TYT', 'Doğal Sistemler', 1, 2),
  ('Coğrafya', 'Coğrafya Biliminin Gelişimi', 'TYT', 'Doğal Sistemler', 1, 3),
  ('Coğrafya', 'Dünya''nın Şekli ve Hareketleri', 'TYT', 'Doğal Sistemler', 1, 4),
  ('Coğrafya', 'Yer ve Zaman', 'TYT', 'Doğal Sistemler', 1, 5),
  ('Coğrafya', 'Atmosfer ve İklim', 'TYT', 'Doğal Sistemler', 1, 6),
  ('Coğrafya', 'Dünya''nın Yapısı ve Oluşumu', 'TYT', 'Doğal Sistemler', 1, 7),
  ('Coğrafya', 'Jeolojik Zamanlar', 'TYT', 'Doğal Sistemler', 1, 8),
  ('Coğrafya', 'İç Kuvvetler', 'TYT', 'Doğal Sistemler', 1, 9),
  ('Coğrafya', 'Kayaçlar', 'TYT', 'Doğal Sistemler', 1, 10),
  ('Coğrafya', 'Türkiye''de İç Kuvvetler', 'TYT', 'Doğal Sistemler', 1, 11),
  ('Coğrafya', 'Dış Kuvvetler', 'TYT', 'Doğal Sistemler', 1, 12),
  ('Coğrafya', 'Türkiye''de Dış Kuvvetler', 'TYT', 'Doğal Sistemler', 1, 13),
  ('Coğrafya', 'Türkiye''nin Yeryüzü Şekilleri', 'TYT', 'Doğal Sistemler', 1, 14),
  ('Coğrafya', 'Su Kaynakları', 'TYT', 'Doğal Sistemler', 1, 15),
  ('Coğrafya', 'Topraklar', 'TYT', 'Doğal Sistemler', 1, 16),
  ('Coğrafya', 'Bitkiler', 'TYT', 'Doğal Sistemler', 1, 17),
  ('Coğrafya', 'Ekosistemlerin Özellikleri ve İşleyişi', 'TYT', 'Doğal Sistemler', 1, 18),
  ('Coğrafya', 'Enerji Akışı ve Madde Döngüleri', 'TYT', 'Doğal Sistemler', 1, 19),
  ('Coğrafya', 'Su Ekosistemleri', 'TYT', 'Doğal Sistemler', 1, 20),
  ('Coğrafya', 'Ekstrem Doğa Olayları', 'TYT', 'Doğal Sistemler', 1, 21),
  ('Coğrafya', 'Küresel İklim Değişikliği', 'TYT', 'Doğal Sistemler', 1, 22),
  ('Coğrafya', 'Yerleşmeler', 'TYT', 'Beşeri Sistemler', 2, 23),
  ('Coğrafya', 'Nüfus', 'TYT', 'Beşeri Sistemler', 2, 24),
  ('Coğrafya', 'Türkiye''de Nüfus', 'TYT', 'Beşeri Sistemler', 2, 25),
  ('Coğrafya', 'Göçler', 'TYT', 'Beşeri Sistemler', 2, 26),
  ('Coğrafya', 'Ekonomik Faaliyetler', 'TYT', 'Beşeri Sistemler', 2, 27),
  ('Coğrafya', 'Nüfus Politikaları', 'TYT', 'Beşeri Sistemler', 2, 28),
  ('Coğrafya', 'Yerleşmelerin Özellikleri', 'TYT', 'Beşeri Sistemler', 2, 29),
  ('Coğrafya', 'Ekonomik Faaliyetler ve Doğal Kaynaklar', 'TYT', 'Beşeri Sistemler', 2, 30),
  ('Coğrafya', 'Türkiye''de Ekonomi', 'TYT', 'Beşeri Sistemler', 2, 31),
  ('Coğrafya', 'Türkiye''nin Bölgesel Kalkınma Projeleri', 'TYT', 'Beşeri Sistemler', 2, 32),
  ('Coğrafya', 'Hizmet Sektörünün Ekonomideki Yeri', 'TYT', 'Beşeri Sistemler', 2, 33),
  ('Coğrafya', 'Türkiye''de Ulaşım, Ticaret ve Turizm', 'TYT', 'Beşeri Sistemler', 2, 34),
  ('Coğrafya', 'Dünya Ticaret Merkezleri', 'TYT', 'Beşeri Sistemler', 2, 35),
  ('Coğrafya', 'Küresel Ticaret', 'TYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 36),
  ('Coğrafya', 'İlk Uygarlıklar', 'TYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 37),
  ('Coğrafya', 'Küresel ve Bölgesel Örgütler', 'TYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 38),
  ('Coğrafya', 'Ülkeler Arası Etkileşim', 'TYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 39),
  ('Coğrafya', 'Bölgeler ve Ülkeler', 'TYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 40),
  ('Coğrafya', 'Doğal Çevreyi Kullanma Biçimleri', 'TYT', 'Çevre ve Toplum', 4, 41),
  ('Coğrafya', 'Doğal Ortamda İnsan Etkileri', 'TYT', 'Çevre ve Toplum', 4, 42),
  ('Coğrafya', 'Afetlerin Genel Özellikleri ve Dağılışı', 'TYT', 'Çevre ve Toplum', 4, 43),
  ('Coğrafya', 'Çevre Sorunları', 'TYT', 'Çevre ve Toplum', 4, 44),
  ('Coğrafya', 'Çevre Sorunlarının Çözümü', 'TYT', 'Çevre ve Toplum', 4, 45),
  ('Coğrafya', 'Türkiye''deki Doğal ve Kültürel Semboller', 'TYT', 'Türkiye Turizmi', 5, 46),
  ('Coğrafya', 'Türkiye''de Turizm Potansiyeli', 'TYT', 'Türkiye Turizmi', 5, 47),
  ('Coğrafya', 'Türkiye''de Turizm Politikaları', 'TYT', 'Türkiye Turizmi', 5, 48),
  ('Coğrafya', 'Turizmin Türkiye Ekonomisindeki Yeri', 'TYT', 'Türkiye Turizmi', 5, 49),
  ('Coğrafya', 'Doğa ve İnsan Etkileşimi', 'AYT', 'Doğal Sistemler', 1, 1),
  ('Coğrafya', 'Bir Bilim Olarak Coğrafya', 'AYT', 'Doğal Sistemler', 1, 2),
  ('Coğrafya', 'Coğrafya Biliminin Gelişimi', 'AYT', 'Doğal Sistemler', 1, 3),
  ('Coğrafya', 'Dünya''nın Şekli ve Hareketleri', 'AYT', 'Doğal Sistemler', 1, 4),
  ('Coğrafya', 'Yer ve Zaman', 'AYT', 'Doğal Sistemler', 1, 5),
  ('Coğrafya', 'Atmosfer ve İklim', 'AYT', 'Doğal Sistemler', 1, 6),
  ('Coğrafya', 'Dünya''nın Yapısı ve Oluşumu', 'AYT', 'Doğal Sistemler', 1, 7),
  ('Coğrafya', 'Jeolojik Zamanlar', 'AYT', 'Doğal Sistemler', 1, 8),
  ('Coğrafya', 'İç Kuvvetler', 'AYT', 'Doğal Sistemler', 1, 9),
  ('Coğrafya', 'Kayaçlar', 'AYT', 'Doğal Sistemler', 1, 10),
  ('Coğrafya', 'Türkiye''de İç Kuvvetler', 'AYT', 'Doğal Sistemler', 1, 11),
  ('Coğrafya', 'Dış Kuvvetler', 'AYT', 'Doğal Sistemler', 1, 12),
  ('Coğrafya', 'Türkiye''de Dış Kuvvetler', 'AYT', 'Doğal Sistemler', 1, 13),
  ('Coğrafya', 'Türkiye''nin Yeryüzü Şekilleri', 'AYT', 'Doğal Sistemler', 1, 14),
  ('Coğrafya', 'Su Kaynakları', 'AYT', 'Doğal Sistemler', 1, 15),
  ('Coğrafya', 'Topraklar', 'AYT', 'Doğal Sistemler', 1, 16),
  ('Coğrafya', 'Bitkiler', 'AYT', 'Doğal Sistemler', 1, 17),
  ('Coğrafya', 'Ekosistemlerin Özellikleri ve İşleyişi', 'AYT', 'Doğal Sistemler', 1, 18),
  ('Coğrafya', 'Enerji Akışı ve Madde Döngüleri', 'AYT', 'Doğal Sistemler', 1, 19),
  ('Coğrafya', 'Su Ekosistemleri', 'AYT', 'Doğal Sistemler', 1, 20),
  ('Coğrafya', 'Ekstrem Doğa Olayları', 'AYT', 'Doğal Sistemler', 1, 21),
  ('Coğrafya', 'Küresel İklim Değişikliği', 'AYT', 'Doğal Sistemler', 1, 22),
  ('Coğrafya', 'Yerleşmeler', 'AYT', 'Beşeri Sistemler', 2, 23),
  ('Coğrafya', 'Nüfus', 'AYT', 'Beşeri Sistemler', 2, 24),
  ('Coğrafya', 'Türkiye''de Nüfus', 'AYT', 'Beşeri Sistemler', 2, 25),
  ('Coğrafya', 'Göçler', 'AYT', 'Beşeri Sistemler', 2, 26),
  ('Coğrafya', 'Ekonomik Faaliyetler', 'AYT', 'Beşeri Sistemler', 2, 27),
  ('Coğrafya', 'Nüfus Politikaları', 'AYT', 'Beşeri Sistemler', 2, 28),
  ('Coğrafya', 'Yerleşmelerin Özellikleri', 'AYT', 'Beşeri Sistemler', 2, 29),
  ('Coğrafya', 'Ekonomik Faaliyetler ve Doğal Kaynaklar', 'AYT', 'Beşeri Sistemler', 2, 30),
  ('Coğrafya', 'Türkiye''de Ekonomi', 'AYT', 'Beşeri Sistemler', 2, 31),
  ('Coğrafya', 'Türkiye''nin Bölgesel Kalkınma Projeleri', 'AYT', 'Beşeri Sistemler', 2, 32),
  ('Coğrafya', 'Hizmet Sektörünün Ekonomideki Yeri', 'AYT', 'Beşeri Sistemler', 2, 33),
  ('Coğrafya', 'Türkiye''de Ulaşım, Ticaret ve Turizm', 'AYT', 'Beşeri Sistemler', 2, 34),
  ('Coğrafya', 'Dünya Ticaret Merkezleri', 'AYT', 'Beşeri Sistemler', 2, 35),
  ('Coğrafya', 'Küresel Ticaret', 'AYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 36),
  ('Coğrafya', 'İlk Uygarlıklar', 'AYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 37),
  ('Coğrafya', 'Küresel ve Bölgesel Örgütler', 'AYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 38),
  ('Coğrafya', 'Ülkeler Arası Etkileşim', 'AYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 39),
  ('Coğrafya', 'Bölgeler ve Ülkeler', 'AYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 40),
  ('Coğrafya', 'Doğal Çevreyi Kullanma Biçimleri', 'AYT', 'Çevre ve Toplum', 4, 41),
  ('Coğrafya', 'Doğal Ortamda İnsan Etkileri', 'AYT', 'Çevre ve Toplum', 4, 42),
  ('Coğrafya', 'Afetlerin Genel Özellikleri ve Dağılışı', 'AYT', 'Çevre ve Toplum', 4, 43),
  ('Coğrafya', 'Çevre Sorunları', 'AYT', 'Çevre ve Toplum', 4, 44),
  ('Coğrafya', 'Çevre Sorunlarının Çözümü', 'AYT', 'Çevre ve Toplum', 4, 45),
  ('Coğrafya', 'Türkiye''deki Doğal ve Kültürel Semboller', 'AYT', 'Türkiye Turizmi', 5, 46),
  ('Coğrafya', 'Türkiye''de Turizm Potansiyeli', 'AYT', 'Türkiye Turizmi', 5, 47),
  ('Coğrafya', 'Türkiye''de Turizm Politikaları', 'AYT', 'Türkiye Turizmi', 5, 48),
  ('Coğrafya', 'Turizmin Türkiye Ekonomisindeki Yeri', 'AYT', 'Türkiye Turizmi', 5, 49),
  ('Türk Dili ve Edebiyatı', 'Edebiyat Nedir?', 'AYT', 'Türk Dili ve Edebiyatına Giriş', 1, 1),
  ('Türk Dili ve Edebiyatı', 'Edebiyatın Bilimlerle ve Güzel Sanatlarla İlişkisi', 'AYT', 'Türk Dili ve Edebiyatına Giriş', 1, 2),
  ('Türk Dili ve Edebiyatı', 'Metinlerin Sınıflandırılması', 'AYT', 'Türk Dili ve Edebiyatına Giriş', 1, 3),
  ('Türk Dili ve Edebiyatı', 'Dilin Kullanımından Doğan Farklılıklar', 'AYT', 'Türk Dili ve Edebiyatına Giriş', 1, 4),
  ('Türk Dili ve Edebiyatı', 'İletişim ve Ögeleri', 'AYT', 'Türk Dili ve Edebiyatına Giriş', 1, 5),
  ('Türk Dili ve Edebiyatı', 'Edebiyatın Dönemlere Ayrılmasındaki Ölçütler', 'AYT', 'Türk Edebiyatının Tarihi Dönemleri', 2, 6),
  ('Türk Dili ve Edebiyatı', 'İslamiyet Öncesi Türk Edebiyatı', 'AYT', 'Türk Edebiyatının Tarihi Dönemleri', 2, 7),
  ('Türk Dili ve Edebiyatı', 'İslamiyet Etkisindeki Türk Edebiyatı', 'AYT', 'Türk Edebiyatının Tarihi Dönemleri', 2, 8),
  ('Türk Dili ve Edebiyatı', 'Batı Etkisinde Gelişen Türk Edebiyatı', 'AYT', 'Türk Edebiyatının Tarihi Dönemleri', 2, 9),
  ('Türk Dili ve Edebiyatı', 'Türkçenin Tarihsel Gelişimi', 'AYT', 'Türk Edebiyatının Tarihi Dönemleri', 2, 10),
  ('Türk Dili ve Edebiyatı', 'Edebiyatın Sanat Akımları ile İlişkisi', 'AYT', 'Edebiyatın Sanat Akımları ile İlişkisi', 3, 11),
  ('Türk Dili ve Edebiyatı', 'Şiir ve Şiirle İlgili Temel Kavramlar', 'AYT', 'Şiir Bilgisi', 4, 12),
  ('Türk Dili ve Edebiyatı', 'Şiirde Ahenk Unsurları', 'AYT', 'Şiir Bilgisi', 4, 13),
  ('Türk Dili ve Edebiyatı', 'Manzume ve Şiir Ayrımı', 'AYT', 'Şiir Bilgisi', 4, 14),
  ('Türk Dili ve Edebiyatı', 'Şiir Türleri', 'AYT', 'Şiir Bilgisi', 4, 15),
  ('Türk Dili ve Edebiyatı', 'İmge ve Söz Sanatları', 'AYT', 'Şiir Bilgisi', 4, 16),
  ('Türk Dili ve Edebiyatı', 'İslamiyetin Kabulünden Önce Türk Şiiri', 'AYT', 'İslamiyet Öncesi Türk Şiiri ve Geçiş Dönemi', 5, 17),
  ('Türk Dili ve Edebiyatı', 'Geçiş Dönemi Türk Edebiyatı', 'AYT', 'İslamiyet Öncesi Türk Şiiri ve Geçiş Dönemi', 5, 18),
  ('Türk Dili ve Edebiyatı', 'Halk Şiiri Özellikleri', 'AYT', 'Halk Şiiri', 6, 19),
  ('Türk Dili ve Edebiyatı', 'Dini - Tasavvufi Türk Şiiri', 'AYT', 'Halk Şiiri', 6, 20),
  ('Türk Dili ve Edebiyatı', 'Divan Şiiri Özellikleri', 'AYT', 'Divan Şiiri', 7, 21),
  ('Türk Dili ve Edebiyatı', 'Divan Şiiri Sanatçıları', 'AYT', 'Divan Şiiri', 7, 22),
  ('Türk Dili ve Edebiyatı', 'Tanzimat Dönemi Şiiri Özellikleri', 'AYT', 'Tanzimat Dönemi''nde Şiir', 8, 23),
  ('Türk Dili ve Edebiyatı', 'Tanzimat Dönemi Sanatçıları', 'AYT', 'Tanzimat Dönemi''nde Şiir', 8, 24),
  ('Türk Dili ve Edebiyatı', 'Servetifünun Dönemi Şiiri', 'AYT', 'Servetifünun Dönemi''nde Şiir', 9, 25),
  ('Türk Dili ve Edebiyatı', 'Fecriati Şiiri', 'AYT', 'Servetifünun Dönemi''nde Şiir', 9, 26),
  ('Türk Dili ve Edebiyatı', 'Saf Şiir', 'AYT', 'Milli Edebiyat Dönemi''nde Şiir', 10, 27),
  ('Türk Dili ve Edebiyatı', 'Milli Edebiyat Dönemi Şiiri Özellikleri ve Şairleri', 'AYT', 'Milli Edebiyat Dönemi''nde Şiir', 10, 28),
  ('Türk Dili ve Edebiyatı', 'Beş Hececiler', 'AYT', 'Milli Edebiyat Dönemi''nde Şiir', 10, 29),
  ('Türk Dili ve Edebiyatı', 'Türkiye Dışındaki Çağdaş Türk Şiiri Özellikleri', 'AYT', 'Milli Edebiyat Dönemi''nde Şiir', 10, 30),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyet Dönemi''nde Saf Şiir Anlayışı Özellikleri ve Temsilcileri', 'AYT', 'Cumhuriyet Dönemi''nde Saf Şiir Anlayışı', 11, 31),
  ('Türk Dili ve Edebiyatı', 'Yedi Meşaleciler', 'AYT', 'Cumhuriyet Dönemi''nde Saf Şiir Anlayışı', 11, 32),
  ('Türk Dili ve Edebiyatı', 'Garip Akımı Özellikleri', 'AYT', 'Garip Akımı', 12, 33),
  ('Türk Dili ve Edebiyatı', 'Garip Akımı Temsilcileri', 'AYT', 'Garip Akımı', 12, 34),
  ('Türk Dili ve Edebiyatı', 'İkinci Yeni Şiiri Özellikleri', 'AYT', 'İkinci Yeni Şiiri', 13, 35),
  ('Türk Dili ve Edebiyatı', 'İkinci Yeni Şiiri Temsilcileri', 'AYT', 'İkinci Yeni Şiiri', 13, 36),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyet Sonrası Toplumcu Eğilimleri Yansıtan Şiir Özellikleri ve Sanatçıları', 'AYT', 'Cumhuriyet Sonrası Toplumcu Eğilimleri Yansıtan Şiir', 14, 37),
  ('Türk Dili ve Edebiyatı', 'Maviciler', 'AYT', 'Cumhuriyet Sonrası Toplumcu Eğilimleri Yansıtan Şiir', 14, 38),
  ('Türk Dili ve Edebiyatı', 'Milli Edebiyat Anlayışını Yansıtan Şiir Özellikleri', 'AYT', 'Milli Edebiyat Anlayışını Yansıtan Şiir', 15, 39),
  ('Türk Dili ve Edebiyatı', 'Milli Edebiyat Anlayışını Yansıtan Şiir Temsilcileri', 'AYT', 'Milli Edebiyat Anlayışını Yansıtan Şiir', 15, 40),
  ('Türk Dili ve Edebiyatı', 'Maveracılar ve Hisar Grubu', 'AYT', 'Dini Değerleri, Geleneğe Duyarlılığı ve Metafizik Anlayışı Öne Çıkaran Şiir', 16, 41),
  ('Türk Dili ve Edebiyatı', '1960 Sonrası Toplumcu Eğilimleri Yansıtan Şiirin Özellikleri', 'AYT', '1960 Sonrası Toplumcu Eğilimleri Yansıtan Şiir', 17, 42),
  ('Türk Dili ve Edebiyatı', '1960 Sonrası Toplumcu Eğilimleri Yansıtan Şiir Temsilcileri', 'AYT', '1960 Sonrası Toplumcu Eğilimleri Yansıtan Şiir', 17, 43),
  ('Türk Dili ve Edebiyatı', '1980 Sonrası Türk Şiirinin Özellikleri', 'AYT', '1980 Sonrası Türk Şiiri', 18, 44),
  ('Türk Dili ve Edebiyatı', '1980 Sonrası Türk Şiirinin Temsilcileri', 'AYT', '1980 Sonrası Türk Şiiri', 18, 45),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyet Sonrası Halk Şiirinin Özellikleri', 'AYT', 'Cumhuriyet Sonrası Halk Şiiri', 19, 46),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyet Sonrası Halk Şiirinin Temsilcileri', 'AYT', 'Cumhuriyet Sonrası Halk Şiiri', 19, 47),
  ('Türk Dili ve Edebiyatı', 'Hikâye ve Yapı Unsurları', 'AYT', 'Hikâye', 20, 48),
  ('Türk Dili ve Edebiyatı', 'Olay ve Durum Hikâyesi', 'AYT', 'Hikâye', 20, 49),
  ('Türk Dili ve Edebiyatı', 'Tanzimat Dönemi''nde Hikâye', 'AYT', 'Hikâye', 20, 50),
  ('Türk Dili ve Edebiyatı', 'Servetifünun Dönemi''nde Hikâye', 'AYT', 'Hikâye', 20, 51),
  ('Türk Dili ve Edebiyatı', 'Milli Edebiyat Dönemi''nde Hikâye', 'AYT', 'Hikâye', 20, 52),
  ('Türk Dili ve Edebiyatı', 'Halk Hikâyeleri', 'AYT', 'Halk Hikâyeleri ve Mesnevi', 21, 53),
  ('Türk Dili ve Edebiyatı', 'Mesnevi', 'AYT', 'Halk Hikâyeleri ve Mesnevi', 21, 54),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyetin İlk Yıllarında Hikâye (1923-1940)', 'AYT', 'Cumhuriyet Dönemi''nde Hikâye', 22, 55),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyet Dönemi''nde Hikâye (1940-1960)', 'AYT', 'Cumhuriyet Dönemi''nde Hikâye', 22, 56),
  ('Türk Dili ve Edebiyatı', 'Küçürek Hikâye Özellikleri', 'AYT', 'Küçürek Hikâye', 23, 57),
  ('Türk Dili ve Edebiyatı', 'Küçürek Hikâye Temsilcileri', 'AYT', 'Küçürek Hikâye', 23, 58),
  ('Türk Dili ve Edebiyatı', 'Modernist Hikâye ve Özellikleri', 'AYT', 'Modernist Hikâye', 24, 59),
  ('Türk Dili ve Edebiyatı', 'Modernist Hikâye Temsilcileri', 'AYT', 'Modernist Hikâye', 24, 60),
  ('Türk Dili ve Edebiyatı', '1960 Sonrası Türk Edebiyatında Hikâye Özellikleri', 'AYT', '1960 Sonrası Türk Edebiyatında Hikâye', 25, 61),
  ('Türk Dili ve Edebiyatı', 'Romanın Yapı Unsurları', 'AYT', 'Roman Türleri ve Yapı Unsurları', 26, 62),
  ('Türk Dili ve Edebiyatı', 'Roman Türleri', 'AYT', 'Roman Türleri ve Yapı Unsurları', 26, 63),
  ('Türk Dili ve Edebiyatı', 'Dünya Edebiyatı Romanı Özellikleri', 'AYT', 'Dünya Edebiyatında Roman', 27, 64),
  ('Türk Dili ve Edebiyatı', 'Dünya Edebiyatında Romanın Tarihçesi', 'AYT', 'Dünya Edebiyatında Roman', 27, 65),
  ('Türk Dili ve Edebiyatı', 'Tanzimat Birinci Dönem Romanı', 'AYT', 'Tanzimat Dönemi''nde Roman', 28, 66),
  ('Türk Dili ve Edebiyatı', 'Tanzimat İkinci Dönem Romanı', 'AYT', 'Tanzimat Dönemi''nde Roman', 28, 67),
  ('Türk Dili ve Edebiyatı', 'Servetifünun Dönemi''nde Roman Özellikleri', 'AYT', 'Servetifünun Dönemi''nde Roman', 29, 68),
  ('Türk Dili ve Edebiyatı', 'Servetifünun Dönemi''nde Romanın Temsilcileri', 'AYT', 'Servetifünun Dönemi''nde Roman', 29, 69),
  ('Türk Dili ve Edebiyatı', 'Milli Edebiyat Dönemi''nde Roman Özellikleri', 'AYT', 'Milli Edebiyat Dönemi''nde Roman', 30, 70),
  ('Türk Dili ve Edebiyatı', 'Milli Edebiyat Dönemi''nde Romanın Temsilcileri', 'AYT', 'Milli Edebiyat Dönemi''nde Roman', 30, 71),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyet Dönemi''nde Roman (1923-1950)', 'AYT', 'Cumhuriyet Dönemi''nde Roman', 31, 72),
  ('Türk Dili ve Edebiyatı', 'Milli ve Dini Duyarlılıkları Yansıtan Roman', 'AYT', 'Cumhuriyet Dönemi''nde Roman', 31, 73),
  ('Türk Dili ve Edebiyatı', 'Toplumcu Gerçekçi Roman', 'AYT', 'Cumhuriyet Dönemi''nde Roman', 31, 74),
  ('Türk Dili ve Edebiyatı', 'Bireyin İç Dünyasını Esas Alan Roman', 'AYT', 'Cumhuriyet Dönemi''nde Roman', 31, 75),
  ('Türk Dili ve Edebiyatı', 'Modernist Roman', 'AYT', 'Cumhuriyet Dönemi''nde Roman', 31, 76),
  ('Türk Dili ve Edebiyatı', '1980 Sonrası Türk Edebiyatında Roman Özellikleri ve Sanatçıları', 'AYT', '1980 Sonrası Türk Edebiyatında Roman', 32, 77),
  ('Türk Dili ve Edebiyatı', 'Türk Dünyası Edebiyatında Roman', 'AYT', '1980 Sonrası Türk Edebiyatında Roman', 32, 78),
  ('Türk Dili ve Edebiyatı', 'Tiyatro Türleri ve Temel Tiyatro Terimleri', 'AYT', 'Tiyatro', 33, 79),
  ('Türk Dili ve Edebiyatı', 'Geleneksel Türk Tiyatrosu', 'AYT', 'Geleneksel ve Modern Türk Tiyatrosu', 34, 80),
  ('Türk Dili ve Edebiyatı', 'Modern Türk Tiyatrosu', 'AYT', 'Geleneksel ve Modern Türk Tiyatrosu', 34, 81),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyet Dönemi''nde Tiyatro (1923-1950)', 'AYT', 'Cumhuriyet Dönemi''nde Tiyatro', 35, 82),
  ('Türk Dili ve Edebiyatı', 'Cumhuriyet Dönemi''nde Tiyatro (1950-1980)', 'AYT', 'Cumhuriyet Dönemi''nde Tiyatro', 35, 83),
  ('Türk Dili ve Edebiyatı', '1980 Sonrası Türk Tiyatrosu Özellikleri', 'AYT', '1980 Sonrası Türk Tiyatrosu', 36, 84),
  ('Türk Dili ve Edebiyatı', 'Masal Türü ve Genel Özellikleri', 'AYT', 'Fabl ve Masal', 37, 85),
  ('Türk Dili ve Edebiyatı', 'Fabl Türü ve Genel Özellikleri', 'AYT', 'Fabl ve Masal', 37, 86),
  ('Türk Dili ve Edebiyatı', 'Biyografi', 'AYT', 'Biyografi ve Otobiyografi', 38, 87),
  ('Türk Dili ve Edebiyatı', 'Otobiyografi', 'AYT', 'Biyografi ve Otobiyografi', 38, 88),
  ('Türk Dili ve Edebiyatı', 'Destan', 'AYT', 'Destan ve Efsane', 39, 89),
  ('Türk Dili ve Edebiyatı', 'Efsane', 'AYT', 'Destan ve Efsane', 39, 90),
  ('Türk Dili ve Edebiyatı', 'Deneme', 'AYT', 'Deneme ve Söylev', 40, 91),
  ('Türk Dili ve Edebiyatı', 'Söylev (Nutuk)', 'AYT', 'Deneme ve Söylev', 40, 92),
  ('Türk Dili ve Edebiyatı', 'Anlam Bakımından Sözcükler', 'AYT', 'Sözcükte Anlam', 41, 93),
  ('Türk Dili ve Edebiyatı', 'Anlam İlişkisi Bakımından Sözcükler', 'AYT', 'Sözcükte Anlam', 41, 94),
  ('Türk Dili ve Edebiyatı', 'Anlatımlarına Göre Cümleler', 'AYT', 'Cümlede Anlam', 42, 95),
  ('Türk Dili ve Edebiyatı', 'Cümle Yorumu', 'AYT', 'Cümlede Anlam', 42, 96),
  ('Türk Dili ve Edebiyatı', 'Cümlede Anlam İlişkileri', 'AYT', 'Cümlede Anlam', 42, 97),
  ('Türk Dili ve Edebiyatı', 'Düşünceyi Geliştirme Yolları', 'AYT', 'Paragrafta Anlam', 43, 98),
  ('Türk Dili ve Edebiyatı', 'Anlatım Biçimleri', 'AYT', 'Paragrafta Anlam', 43, 99),
  ('Türk Dili ve Edebiyatı', 'Paragrafta Konu, Ana Düşünce ve Yardımcı Düşünceler', 'AYT', 'Paragrafta Anlam', 43, 100),
  ('Türk Dili ve Edebiyatı', 'Paragrafta Yapı', 'AYT', 'Paragrafta Anlam', 43, 101),
  ('Türk Dili ve Edebiyatı', 'İyi Bir Anlatımda Bulunması Gereken Özellikler', 'AYT', 'Paragrafta Anlam', 43, 102);

-- 5) View'i geri kur (0031'deki tanımın aynısı).
create view public.konu_havuz as
select
  k.id                       as konu_id,
  k.subject,
  k.ad,
  k.sinav,
  k.sira,
  k.unite,
  k.unite_sira,
  count(q.id)                as soru_sayisi,
  count(q.id) filter (where q.difficulty = 'kolay') as kolay,
  count(q.id) filter (where q.difficulty = 'orta')  as orta,
  count(q.id) filter (where q.difficulty = 'zor')   as zor
from public.konular k
left join public.kazanim_konu kk on kk.konu_id = k.id
left join public.yks_ai_questions q
       on q.kazanim_id = kk.kazanim_id
      and q.verified = true
      and q.karantina = false
group by k.id, k.subject, k.ad, k.sinav, k.sira, k.unite, k.unite_sira;

comment on view public.konu_havuz is
  'Konu başına ÇÖZÜLEBİLİR soru adedi (verified ∧ ¬karantina) + zorluk kırılımı + ünite. '
  'Yalnız service_role okur — authenticated''a GRANT verilmez (RLS dolanma yüzeyi).';

commit;

-- =============================================================================
-- DOĞRULAMA:
--   -- 1) Toplam 752 + korunan 61 = 813 beklenir:
--   select count(*) from public.konular;
--
--   -- 2) Ders kırılımı:
--   select subject, sinav, count(*) from public.konular group by 1,2 order by 1,2;
--
--   -- 3) Ünitesiz konu KALMAMALI (0 satır):
--   select subject, sinav, ad from public.konular where unite is null;
--
--   -- 4) En kalabalık üniteler — 0031'deki "10'u geçmesin" kuralı artık GEÇERSİZ.
--   --    Kunduz derinliğinde Coğrafya/Doğal Sistemler 22, Fizik/Elektrik ve Manyetizma 12
--   --    konu içeriyor; bu bilinçli. Arayüz üniteyi liste olarak açıyor, kart olarak değil.
--   select subject, sinav, unite, count(*) c from public.konular
--    group by 1,2,3 order by c desc limit 10;
-- =============================================================================
